# Generated by Django 5.1.5 on 2025-10-07 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agentprompt",
            name="agent_name",
            field=models.CharField(
                choices=[
                    ("admin_agent", "Admin Agent"),
                    ("analytics_agent", "Analytics Agent"),
                    ("bundles_agent", "Bundles Agent"),
                    ("custom_object_agent", "Custom Object Agent"),
                    ("product_agent", "Product Agent"),
                    ("quote_agent", "Quote Agent"),
                    ("action_trigger_agent", "Action Trigger Agent"),
                ],
                max_length=50,
            ),
        ),
    ]
