# Generated by Django 5.2.4 on 2025-09-25 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attitude', models.TextField(help_text='Describe la actitud o tono que debe usar el agente')),
                ('emoji_successful', models.CharField(blank=True, max_length=10, null=True)),
                ('emoji_failed', models.CharField(blank=True, max_length=10, null=True)),
                ('natural', models.BooleanField(default=True, help_text='Usar lenguaje natural y simple')),
                ('technical', models.BooleanField(default=False, help_text='Usar un lenguaje más técnico')),
                ('emoji_rich', models.BooleanField(default=False, help_text='Usar emojis en las respuestas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Agent Response',
                'verbose_name_plural': 'Agent Responses',
            },
        ),
        migrations.CreateModel(
            name='AgentPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_name', models.CharField(choices=[('admin_agent', 'Admin Agent'), ('analytics_agent', 'Analytics Agent'), ('bundles_agent', 'Bundles Agent'), ('custom_object_agent', 'Custom Object Agent'), ('product_agent', 'Product Agent'), ('quote_agent', 'Quote Agent')], max_length=50)),
                ('method', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete')], max_length=20)),
                ('system_instructions', models.TextField()),
                ('agent_summary', models.TextField(blank=True, null=True)),
                ('temperature', models.FloatField(default=0.7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent_response', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prompts', to='agents.agentresponse')),
            ],
            options={
                'verbose_name': 'Agent Prompt',
                'verbose_name_plural': 'Agent Prompts',
                'unique_together': {('agent_name', 'method')},
            },
        ),
    ]
