# Generated by Django 5.2.4 on 2025-07-24 21:17

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_agentsessionstate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AgentSessionState',
            new_name='SessionState',
        ),
    ]
