# Generated by Django 5.2.4 on 2025-09-25 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_agentresponse_agentprompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentprompt',
            name='system_rules',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='agentprompt',
            name='temperature',
            field=models.FloatField(default=0.8),
        ),
        migrations.AlterField(
            model_name='agentresponse',
            name='attitude',
            field=models.TextField(help_text='Describe the attitude or tone the agent should use'),
        ),
        migrations.AlterField(
            model_name='agentresponse',
            name='emoji_rich',
            field=models.BooleanField(default=False, help_text='Use emojis in the responses'),
        ),
        migrations.AlterField(
            model_name='agentresponse',
            name='natural',
            field=models.BooleanField(default=True, help_text='Use natural and simple language'),
        ),
        migrations.AlterField(
            model_name='agentresponse',
            name='technical',
            field=models.BooleanField(default=False, help_text='Use more technical language'),
        ),
    ]
