# Generated by Django 5.2.4 on 2025-09-25 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0003_agentprompt_system_rules_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AgentResponse',
            new_name='AgentMessage',
        ),
    ]
