# Generated by Django 5.1.5 on 2025-12-09 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0003_seed_bundles_update_prompt"),
    ]

    operations = [
        migrations.AlterField(
            model_name="singlerecordlayout",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
