# Generated by Django 5.1.5 on 2026-09-15 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0004_alter_singlerecordlayout_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="LLMConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="When enabled, these settings override the LLM_* / OPENAI_* environment variables.",
                    ),
                ),
                (
                    "api_key_encrypted",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Encrypted API key for the provider. Stored encrypted at rest.",
                    ),
                ),
                (
                    "base_url",
                    models.CharField(
                        blank=True,
                        help_text="OpenAI-compatible base URL, e.g. https://api.deepseek.com. Blank falls back to environment.",
                        max_length=255,
                    ),
                ),
                (
                    "model",
                    models.CharField(
                        blank=True,
                        help_text="Default model, e.g. deepseek-chat. Blank falls back to LLM_MODEL / gpt-4o-mini.",
                        max_length=100,
                    ),
                ),
                (
                    "model_classifier",
                    models.CharField(
                        blank=True,
                        help_text="Model for intent routing/classification (optional).",
                        max_length=100,
                    ),
                ),
                (
                    "model_structured",
                    models.CharField(
                        blank=True,
                        help_text="Model for JSON extraction (optional).",
                        max_length=100,
                    ),
                ),
                (
                    "model_reasoning",
                    models.CharField(
                        blank=True,
                        help_text="Model for general answers / reasoning (optional).",
                        max_length=100,
                    ),
                ),
                (
                    "json_mode",
                    models.BooleanField(
                        default=True,
                        help_text="Whether chat/JSON calls request response_format=json_object.",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "LLM Config",
                "verbose_name_plural": "LLM Config",
                "ordering": ("-id",),
            },
        ),
    ]
