# Generated by Django 5.2.4 on 2025-09-25 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0004_rename_agentresponse_agentmessage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agentprompt',
            old_name='agent_response',
            new_name='agent_message',
        ),
    ]
