# Generated by Django 5.2.4 on 2025-09-25 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0005_rename_agent_response_agentprompt_agent_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentprompt',
            name='agent_message',
            field=models.TextField(),
        ),
        migrations.DeleteModel(
            name='AgentMessage',
        ),
    ]
