# Generated by Django 5.2.4 on 2025-09-25 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0006_alter_agentprompt_agent_message_delete_agentmessage'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='agentprompt',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='agentprompt',
            name='function',
            field=models.CharField(blank=True, help_text='The specific function of the LLM', max_length=50, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='agentprompt',
            unique_together={('agent_name', 'method', 'function')},
        ),
    ]
