<<<<<<< HEAD
# Generated by Django 5.1.5 on 2025-09-16 21:41
=======
# Generated by Django 5.2.4 on 2025-09-09 20:46
>>>>>>> sympletech_sept_j

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HubspotToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_id",
                    models.CharField(default="default", max_length=255, unique=True),
                ),
                ("access_token", models.TextField()),
                ("refresh_token", models.TextField(blank=True, null=True)),
                ("expires_in", models.IntegerField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("token_type", models.CharField(blank=True, max_length=50, null=True)),
                ("scope", models.TextField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
