# Generated by Django 5.1.5 on 2026-02-19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cpq", "0041_alter_opportunity_expected_close_date"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("tenant_id", models.CharField(db_index=True, max_length=64)),
                ("run_id", models.CharField(db_index=True, max_length=64)),
                ("source", models.CharField(default="api", max_length=32)),
                ("idempotency_key", models.CharField(blank=True, default="", max_length=255)),
                ("tenant_resolution_source", models.CharField(blank=True, default="", max_length=32)),
                ("duplicate_request_detected", models.BooleanField(default=False)),
                ("entity_type", models.CharField(max_length=32)),
                ("entity_id", models.CharField(max_length=128)),
                ("event_type", models.CharField(max_length=64)),
                ("details_json", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["tenant_id", "run_id"], name="agentcpq_de_tenant__4f2529_idx"),
                    models.Index(fields=["tenant_id", "entity_type", "entity_id"], name="agentcpq_de_tenant__cf4f5d_idx"),
                    models.Index(fields=["tenant_id", "event_type"], name="agentcpq_de_tenant__b13ed9_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="PolicyConfig",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("tenant_id", models.CharField(db_index=True, max_length=64)),
                ("version", models.CharField(max_length=32)),
                ("is_active", models.BooleanField(default=True)),
                ("config_json", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["tenant_id", "is_active"], name="agentcpq_de_tenant__a547c2_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(fields=("tenant_id", "version"), name="uniq_policyconfig_tenant_version"),
                ],
            },
        ),
        migrations.CreateModel(
            name="SystemAuditEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("source", models.CharField(default="api", max_length=32)),
                ("event_type", models.CharField(max_length=64)),
                ("request_meta_json", models.JSONField(blank=True, default=dict)),
                ("idempotency_key_if_present", models.CharField(blank=True, default="", max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["event_type", "created_at"], name="agentcpq_de_event_t_819f5d_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="DealPacket",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("tenant_id", models.CharField(db_index=True, max_length=64)),
                ("idempotency_key", models.CharField(max_length=255)),
                ("request_fingerprint", models.CharField(max_length=64)),
                (
                    "external_ref_type",
                    models.CharField(
                        choices=[("opportunity", "Opportunity"), ("quote", "Quote"), ("deal_packet", "Deal Packet")],
                        max_length=24,
                    ),
                ),
                ("external_ref_id", models.CharField(max_length=128)),
                ("crm_source", models.CharField(blank=True, default="", max_length=64)),
                ("payload_json", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("needs_info", "Needs Info"),
                            ("in_approval", "In Approval"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="draft",
                        max_length=32,
                    ),
                ),
                ("decision_summary", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dealdesk_packets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["tenant_id", "external_ref_type", "external_ref_id"], name="agentcpq_de_tenant__e50f99_idx"),
                    models.Index(fields=["tenant_id", "status"], name="agentcpq_de_tenant__37025a_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(fields=("tenant_id", "idempotency_key"), name="uniq_dealpacket_tenant_idempotency"),
                ],
            },
        ),
        migrations.CreateModel(
            name="PolicyEvaluation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("tenant_id", models.CharField(db_index=True, max_length=64)),
                ("policy_version", models.CharField(max_length=32)),
                ("results_json", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "deal_packet",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="policy_evaluations", to="dealdesk.dealpacket"),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["tenant_id", "deal_packet"], name="agentcpq_de_tenant__14eb1e_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="DealDeskApprovalInstance",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("tenant_id", models.CharField(db_index=True, max_length=64)),
                (
                    "routing_mode",
                    models.CharField(
                        choices=[("template_used", "Template Used"), ("instance_fallback", "Instance Fallback")],
                        max_length=32,
                    ),
                ),
                ("instance_key", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "deal_packet",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="approval_instances", to="dealdesk.dealpacket"),
                ),
                (
                    "instance_workflow_ref",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dealdesk_runtime_instances",
                        to="cpq.approvalworkflow",
                    ),
                ),
                (
                    "quoteapproval",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dealdesk_instances",
                        to="cpq.quoteapproval",
                    ),
                ),
                (
                    "template_workflow_ref",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dealdesk_template_instances",
                        to="cpq.approvalworkflow",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["tenant_id", "deal_packet"], name="agentcpq_de_tenant__e4fdb8_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(fields=("tenant_id", "deal_packet", "instance_key"), name="uniq_dealdesk_instance_key"),
                ],
            },
        ),
        migrations.CreateModel(
            name="SLATimer",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("tenant_id", models.CharField(db_index=True, max_length=64)),
                ("target_role", models.CharField(max_length=255)),
                ("due_at", models.DateTimeField()),
                ("breached", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deal_packet",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="sla_timers", to="dealdesk.dealpacket"),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["tenant_id", "breached"], name="agentcpq_de_tenant__ca867e_idx"),
                    models.Index(fields=["tenant_id", "due_at"], name="agentcpq_de_tenant__1bf60f_idx"),
                ],
            },
        ),
    ]
