<<<<<<< HEAD
# Generated by Django 5.1.5 on 2025-09-16 21:41
=======
# Generated by Django 5.2.4 on 2025-09-09 20:46
>>>>>>> sympletech_sept_j

import cpq.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ApprovalRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "priority",
                    models.IntegerField(
                        default=0,
                        help_text="Higher priority rules are evaluated first.",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ApprovalWorkflow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="BusinessRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255)),
                ("description", models.CharField(max_length=255)),
                (
                    "rule_type",
                    models.CharField(
                        choices=[
                            ("validation", "Validation"),
                            ("inclusion", "Inclusion"),
                            ("exclusion", "Exclusion"),
                        ],
                        default="validation",
                        max_length=20,
                    ),
                ),
                (
                    "target_type",
                    models.CharField(
                        choices=[
                            ("quote", "Quote"),
                            ("quote_line", "Quote Line"),
                            ("product", "Product"),
                        ],
                        default="quote_line",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(
                        default=0, help_text="Higher priority rules run first."
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True,
                        help_text="Message shown when the rule is triggered.",
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "conditions",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of conditions for the rule.",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
<<<<<<< HEAD
            name="Pricebook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "salesforce_id",
                    models.CharField(blank=True, max_length=18, null=True, unique=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="QuoteDocumentSettings",
=======
            name='Pricebook',
>>>>>>> sympletech_sept_j
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("show_company_name", models.BooleanField(default=True)),
                ("show_company_address", models.BooleanField(default=True)),
                ("show_company_phone", models.BooleanField(default=False)),
                ("show_company_email", models.BooleanField(default=True)),
                ("show_company_domain", models.BooleanField(default=False)),
                ("show_company_logo", models.BooleanField(default=True)),
                ("show_account_name", models.BooleanField(default=True)),
                ("show_account_website", models.BooleanField(default=False)),
                ("show_account_phone", models.BooleanField(default=False)),
                ("show_quote_opportunity", models.BooleanField(default=True)),
                ("show_quote_status", models.BooleanField(default=True)),
                ("show_quote_created_at", models.BooleanField(default=True)),
                ("show_quote_expires_at", models.BooleanField(default=True)),
                ("show_quote_notes", models.BooleanField(default=True)),
                ("show_quote_tax_information", models.BooleanField(default=True)),
                ("show_quote_tax_percentage", models.BooleanField(default=True)),
                ("show_quote_tax_amount", models.BooleanField(default=True)),
                (
                    "quote_tax",
                    models.DecimalField(decimal_places=2, default=7.25, max_digits=10),
                ),
                ("show_line_discount_percentage", models.BooleanField(default=False)),
                ("show_line_discount_amount", models.BooleanField(default=False)),
                ("show_line_discount", models.BooleanField(default=True)),
                (
                    "rendered_fields",
                    models.JSONField(
                        blank=True,
                        default=cpq.models.QuoteDocumentSettings.default_rendered_fields,
                    ),
                ),
                (
                    "omitted_fields",
                    models.JSONField(
                        blank=True,
                        default=cpq.models.QuoteDocumentSettings.default_omitted_fields,
                    ),
                ),
                (
                    "line_description_detail_level",
                    models.CharField(
                        choices=[("short", "Short"), ("long", "Modern")],
                        default="short",
                        help_text="Select the quote line description detail level.",
                        max_length=20,
                    ),
                ),
                ("show_subscription_term", models.BooleanField(default=True)),
                ("show_sign", models.BooleanField(default=True)),
                (
                    "template_style",
                    models.CharField(
                        choices=[("classic", "Classic"), ("modern", "Modern")],
                        default="modern",
                        help_text="Select the design style of the PDF template",
                        max_length=20,
                    ),
                ),
                ("terms_and_conditions", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="QuoteUIRender",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("show_quote_account", models.BooleanField(default=True)),
                ("show_quote_opportunity", models.BooleanField(default=True)),
                ("show_quote_created_at", models.BooleanField(default=True)),
                ("show_quote_expires_at", models.BooleanField(default=True)),
                ("show_quote_discount", models.BooleanField(default=True)),
                (
                    "rendered_fields",
                    models.JSONField(
                        blank=True,
                        default=cpq.models.QuoteUIRender.default_rendered_fields,
                    ),
                ),
                (
                    "omitted_fields",
                    models.JSONField(
                        blank=True,
                        default=cpq.models.QuoteUIRender.default_omitted_fields,
                    ),
                ),
                ("show_quote_subtotal", models.BooleanField(default=True)),
                ("show_quote_net_amount", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Tenant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tenant_id", models.CharField(blank=True, max_length=20, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("domain", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "contact_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "street_address",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("city", models.CharField(blank=True, max_length=100, null=True)),
                ("state", models.CharField(blank=True, max_length=100, null=True)),
                ("version", models.CharField(default="1.0.0", max_length=50)),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to=cpq.models.temp_logo_path
                    ),
                ),
                (
                    "billing_contact",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                (
                    "plan",
                    models.CharField(
                        choices=[
                            ("solo", "Solo"),
                            ("team", "Team"),
                            ("pro", "Pro"),
                            ("business", "Business"),
                            ("enterprise", "Enterprise"),
                        ],
                        default="solo",
                        max_length=20,
                    ),
                ),
                ("actions_limit", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "primary_color",
                    models.CharField(blank=True, max_length=7, null=True),
                ),
                (
                    "secondary_color",
                    models.CharField(blank=True, max_length=7, null=True),
                ),
                (
                    "api_key",
                    models.CharField(
                        default=cpq.models.gen_api_key,
                        editable=False,
                        help_text="Public API key, auto-generated",
                        max_length=43,
                        null=True,
                    ),
                ),
                (
                    "api_secret",
                    models.CharField(
                        default=cpq.models.gen_api_key,
                        editable=False,
                        help_text="Private key used for request signing",
                        max_length=43,
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("industry", models.CharField(blank=True, max_length=255, null=True)),
                ("website", models.URLField(blank=True, null=True)),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "accid",
                    models.CharField(
                        db_index=True, editable=False, max_length=18, unique=True
                    ),
                ),
                (
                    "external_id",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                ("street", models.CharField(blank=True, max_length=255, null=True)),
                ("city", models.CharField(blank=True, max_length=100, null=True)),
                ("state", models.CharField(blank=True, max_length=100, null=True)),
                ("zip_code", models.CharField(blank=True, max_length=20, null=True)),
                ("tenant_id", models.CharField(max_length=30, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_accounts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="accounts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ActionUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(max_length=100)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "related_object_type",
                    models.CharField(
                        blank=True,
                        help_text="Type of object this action is related to (e.g., Quote, Product, Approval)",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "related_object_id",
                    models.CharField(
                        blank=True,
                        help_text="ID of the related object (e.g., Q-0001, PROD-001)",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="action_usages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="ApprovalStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sequence", models.PositiveIntegerField(default=1)),
                (
                    "approver_role",
                    models.CharField(
                        help_text="Role required to approve this step", max_length=255
                    ),
                ),
                (
                    "rule",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="cpq.approvalrule",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="approvalrule",
            name="workflow",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rules",
                to="cpq.approvalworkflow",
            ),
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(blank=True, max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("company", models.CharField(blank=True, max_length=255)),
                ("job_title", models.CharField(blank=True, max_length=100)),
                ("notes", models.TextField(blank=True)),
                (
                    "external_id",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "contactId",
                    models.CharField(
                        db_index=True, editable=False, max_length=18, unique=True
                    ),
                ),
                ("is_primary", models.BooleanField(default=False)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contacts",
                        to="cpq.account",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_contacts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CustomObject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("label", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_custom_objects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_custom_objects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Custom Object",
                "verbose_name_plural": "Custom Objects",
            },
        ),
        migrations.CreateModel(
            name="CustomField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(blank=True, max_length=100)),
                ("name", models.CharField(max_length=100)),
                ("crm", models.CharField(max_length=50)),
                ("object_type", models.CharField(max_length=50)),
                ("data_type", models.CharField(max_length=50)),
                ("required", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "lookup_model",
                    models.CharField(
                        blank=True,
                        help_text="Format: 'app_label.ModelName' (e.g., 'cpq.Account')",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "options",
                    models.JSONField(
                        blank=True,
                        help_text="Used for Dropdown data_type. List of options.",
                        null=True,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="creted_custom_fields",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_custom_fields",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "custom_object",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_fields",
                        to="cpq.customobject",
                    ),
                ),
            ],
            options={
                "verbose_name": "Custom Field",
                "verbose_name_plural": "Custom Fields",
            },
        ),
        migrations.CreateModel(
            name="CustomRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "custom_identifier",
                    models.CharField(blank=True, max_length=10, null=True, unique=True),
                ),
                ("record_id", models.UUIDField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_custom_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "object_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="records",
                        to="cpq.customobject",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_custom_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CustomFieldValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.PositiveIntegerField(blank=True, null=True)),
                ("value", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="values",
                        to="cpq.customfield",
                    ),
                ),
                (
                    "record",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_field_values",
                        to="cpq.customrecord",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
<<<<<<< HEAD
            name="EmailAlert",
=======
            name='EmailAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('trigger', models.CharField(choices=[('lead_created', 'New Lead Created'), ('account_created', 'New Account Created'), ('opportunity_created', 'New Opportunity Created'), ('opportunity_closed_won', 'Opportunity Closed Won'), ('opportunity_closed_lost', 'Opportunity Closed Lost'), ('quote_sent_for_approval', 'Quote Sent for Approval'), ('quote_approved', 'Quote Approved'), ('quote_rejected', 'Quote Rejected'), ('quote_expiring', 'Quote Expiring Soon'), ('subscription_renewal', 'Subscription Renewal Reminder')], max_length=50)),
                ('native_object', models.CharField(blank=True, choices=[('Lead', 'Lead'), ('Account', 'Account'), ('Opportunity', 'Opportunity'), ('Quote', 'Quote'), ('Subscription', 'Subscription')], help_text='Select a native object', max_length=50, null=True)),
                ('recipients_roles', models.CharField(blank=True, help_text='Select the role of the recipients', max_length=50, null=True)),
                ('recipients_external', models.TextField(blank=True, help_text='External emails separated by commas', null=True)),
                ('offset_days', models.IntegerField(blank=True, help_text='E.g., send 7 days before the expiration date (for subscriptions, quotes, etc.)', null=True)),
                ('scheduled_cron', models.CharField(blank=True, help_text="Cron format or text like 'every other Friday at noon'", max_length=100, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_alerts_created', to=settings.AUTH_USER_MODEL)),
                ('custom_object', models.ForeignKey(blank=True, help_text='Select a custom object', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cpq.customobject')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_alerts_updated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmailAlertRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cpq.emailalert')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('email_alert', 'user')},
            },
        ),
        migrations.AddField(
            model_name='emailalert',
            name='recipients_users',
            field=models.ManyToManyField(blank=True, related_name='email_alerts', through='cpq.EmailAlertRecipient', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Lead',
>>>>>>> sympletech_sept_j
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "trigger",
                    models.CharField(
                        choices=[
                            ("lead_created", "New Lead Created"),
                            ("account_created", "New Account Created"),
                            ("opportunity_created", "New Opportunity Created"),
                            ("opportunity_closed_won", "Opportunity Closed Won"),
                            ("opportunity_closed_lost", "Opportunity Closed Lost"),
                            ("quote_sent_for_approval", "Quote Sent for Approval"),
                            ("quote_approved", "Quote Approved"),
                            ("quote_rejected", "Quote Rejected"),
                            ("quote_expiring", "Quote Expiring Soon"),
                            ("subscription_renewal", "Subscription Renewal Reminder"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "native_object",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Lead", "Lead"),
                            ("Account", "Account"),
                            ("Opportunity", "Opportunity"),
                            ("Quote", "Quote"),
                            ("Subscription", "Subscription"),
                        ],
                        help_text="Select a native object",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "recipients_roles",
                    models.CharField(
                        blank=True,
                        help_text="Select the role of the recipients",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "recipients_external",
                    models.TextField(
                        blank=True,
                        help_text="External emails separated by commas",
                        null=True,
                    ),
                ),
                (
                    "offset_days",
                    models.IntegerField(
                        blank=True,
                        help_text="E.g., send 7 days before the expiration date (for subscriptions, quotes, etc.)",
                        null=True,
                    ),
                ),
                (
                    "scheduled_cron",
                    models.CharField(
                        blank=True,
                        help_text="Cron format or text like 'every other Friday at noon'",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="email_alerts_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "custom_object",
                    models.ForeignKey(
                        blank=True,
                        help_text="Select a custom object",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="cpq.customobject",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="email_alerts_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EmailAlertRecipient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email_alert",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="cpq.emailalert"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("email_alert", "user")},
            },
        ),
        migrations.AddField(
            model_name="emailalert",
            name="recipients_users",
            field=models.ManyToManyField(
                blank=True,
                related_name="email_alerts",
                through="cpq.EmailAlertRecipient",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="Lead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                (
                    "leadId",
                    models.CharField(
                        db_index=True, editable=False, max_length=18, unique=True
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        help_text="e.g., Website, Referral, LinkedIn",
                        max_length=100,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("qualified", "Qualified"),
                            ("converted", "Converted"),
                            ("disqualified", "Disqualified"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("assigned_to", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "contact",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="leads",
                        to="cpq.contact",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_leads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="owned_leads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Opportunity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("appointmentscheduled", "Appointment Scheduled"),
                            ("qualifiedtobuy", "Qualified to Buy"),
                            ("presentationscheduled", "Presentation Scheduled"),
                            ("decisionmakerboughtin", "Decision Maker Bought-In"),
                            ("contractsent", "Contract Sent"),
                            ("closedwon", "Closed Won"),
                            ("closedlost", "Closed Lost"),
                        ],
                        default="Prospecting",
                        max_length=50,
                    ),
                ),
                ("expected_close_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "oppid",
                    models.CharField(
                        db_index=True, editable=False, max_length=18, unique=True
                    ),
                ),
                (
                    "hs_deal_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        editable=False,
                        max_length=18,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="opportunities",
                        to="cpq.account",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_opportunities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="owned_opportunities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Opportunity",
                "verbose_name_plural": "Opportunities",
            },
        ),
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject", models.CharField(max_length=255)),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("call", "Call"),
                            ("email", "Email"),
                            ("meeting", "Meeting"),
                            ("task", "Task"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_started", "Not Started"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("deferred", "Deferred"),
                        ],
                        default="not_started",
                        max_length=50,
                    ),
                ),
                ("due_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "activityid",
                    models.CharField(
                        db_index=True, editable=False, max_length=18, unique=True
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_activities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activities",
                        to="cpq.contact",
                    ),
                ),
                (
                    "lead",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activities",
                        to="cpq.lead",
                    ),
                ),
                (
                    "opportunity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activities",
                        to="cpq.opportunity",
                    ),
                ),
            ],
            options={
                "verbose_name": "Activity",
                "verbose_name_plural": "Activities",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("sku", models.CharField(max_length=100, unique=True)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("is_subscription", models.BooleanField(default=False)),
                ("term", models.IntegerField(blank=True, null=True)),
                ("is_bundle", models.BooleanField(default=False)),
                ("family", models.CharField(max_length=50)),
                (
                    "prdid",
                    models.CharField(
                        db_index=True, editable=False, max_length=18, unique=True
                    ),
                ),
                (
                    "external_id",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("description", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_products",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_products",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PricingRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("min_quantity", models.PositiveIntegerField(default=1)),
                ("max_quantity", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "discount_percentage",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                (
                    "fixed_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pricing_rules",
                        to="cpq.product",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PricebookEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "salesforce_id",
                    models.CharField(blank=True, max_length=18, null=True, unique=True),
                ),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "pricebook",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="cpq.pricebook",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pricebook_entries",
                        to="cpq.product",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Option",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("is_required", models.BooleanField(default=False)),
                ("min_quantity", models.PositiveIntegerField(default=1)),
                ("max_quantity", models.PositiveIntegerField(default=10)),
                ("default_selected", models.BooleanField(default=True)),
                ("group_name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "parent_product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="cpq.product",
                    ),
                ),
                (
                    "product_option",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="included_in",
                        to="cpq.product",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rule_type",
                    models.CharField(
                        choices=[
                            ("Dependency", "Dependency"),
                            ("Exclusion", "Exclusion"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rules",
                        to="cpq.product",
                    ),
                ),
                (
                    "related_product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="related_rules",
                        to="cpq.product",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Quote",
            fields=[
<<<<<<< HEAD
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "sf_opportunity_id",
                    models.CharField(blank=True, max_length=18, null=True),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                ("net_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "tax_percentage",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "tax_amount",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Draft", "Draft"),
                            ("Pending Approval", "Pending Approval"),
                            ("Approved", "Approved"),
                            ("Rejected", "Rejected"),
                            ("Closed", "Closed"),
                        ],
                        default="Draft",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "discount_type",
                    models.CharField(
                        choices=[("percentage", "Percentage"), ("amount", "Amount")],
                        default="percentage",
                        max_length=20,
                    ),
                ),
                (
                    "discount_percentage",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                (
                    "discount_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "expiration_date",
                    models.DateTimeField(
                        blank=True,
                        default=cpq.models.Quote.default_expiration_date,
                        null=True,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "qteid",
                    models.CharField(
                        db_index=True, editable=False, max_length=18, unique=True
                    ),
                ),
                (
                    "hs_deal_id",
                    models.CharField(
                        blank=True,
                        help_text="The HubSpot Deal ID linked to this quote",
                        max_length=64,
                        null=True,
                    ),
                ),
                (
                    "hs_primary",
                    models.BooleanField(
                        default=False,
                        help_text="Marks this quote as the primary quote for the HubSpot deal",
                    ),
                ),
                ("synced", models.BooleanField(default=False)),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quotes",
                        to="cpq.account",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_quotes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "opportunity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quotes",
                        to="cpq.opportunity",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="owned_quotes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
=======
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('sf_opportunity_id', models.CharField(blank=True, max_length=18, null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tax_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Pending Approval', 'Pending Approval'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Closed', 'Closed')], default='Draft', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage'), ('amount', 'Amount')], default='percentage', max_length=20)),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('expiration_date', models.DateTimeField(blank=True, default=cpq.models.Quote.default_expiration_date, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('qteid', models.CharField(db_index=True, editable=False, max_length=18, unique=True)),
                ('hs_deal_id', models.CharField(blank=True, help_text='The HubSpot Deal ID linked to this quote', max_length=64, null=True)),
                ('hs_primary', models.BooleanField(default=False, help_text='Marks this quote as the primary quote for the HubSpot deal')),
                ('synced', models.BooleanField(default=False)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='cpq.account')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_quotes', to=settings.AUTH_USER_MODEL)),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='cpq.opportunity')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_quotes', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_quotes', to=settings.AUTH_USER_MODEL)),
>>>>>>> sympletech_sept_j
            ],
        ),
        migrations.AddField(
            model_name="opportunity",
            name="primary_quote",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="opportunity_primary_quote",
                to="cpq.quote",
            ),
        ),
        migrations.CreateModel(
            name="QuoteApproval",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "approved_by",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Approved", "Approved"),
                            ("Rejected", "Rejected"),
                        ],
                        default="Pending",
                        max_length=50,
                    ),
                ),
                (
                    "quote",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approvals",
                        to="cpq.quote",
                    ),
                ),
                (
                    "step",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cpq.approvalstep",
                    ),
                ),
                (
                    "workflow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cpq.approvalworkflow",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="QuoteLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("quantity", models.IntegerField(default=1)),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "special_price",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "discount_type",
                    models.CharField(
                        blank=True,
                        choices=[("percentage", "Percentage"), ("amount", "Amount")],
                        default="percentage",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "discount_percentage",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                (
                    "discount_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("total_price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "external_id",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                ("is_subscription", models.BooleanField(default=False)),
                ("is_bundle_parent", models.BooleanField(default=False)),
                ("is_bundle_child", models.BooleanField(default=False)),
                ("is_bundle_component_selected", models.BooleanField(default=False)),
                (
                    "billing_frequency",
                    models.CharField(
                        choices=[
                            ("monthly", "monthly"),
                            ("quarterly", "quarterly"),
                            ("annual", "annual"),
                            ("one_time", "one_time"),
                        ],
                        default="one_time",
                        max_length=20,
                    ),
                ),
                ("term", models.PositiveIntegerField(blank=True, null=True)),
                ("billing_start_date", models.DateField(blank=True, null=True)),
                ("billing_end_date", models.DateField(blank=True, null=True)),
                ("sku", models.CharField(blank=True, max_length=100, null=True)),
                ("synced_to_crm", models.BooleanField(default=False)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "tax_rate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_quote_lines",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent_line",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="child_lines",
                        to="cpq.quoteline",
                    ),
                ),
                (
                    "parent_quote",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parent_quote_lines",
                        to="cpq.quote",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quote_lines",
                        to="cpq.product",
                    ),
                ),
                (
                    "product_option",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="cpq.option",
                    ),
                ),
                (
                    "quote",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quote_lines",
                        to="cpq.quote",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("serial_number", models.CharField(max_length=255, unique=True)),
                (
                    "assigned_to",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("activated_date", models.DateField(blank=True, null=True)),
                ("deactivated_date", models.DateField(blank=True, null=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assets",
                        to="cpq.product",
                    ),
                ),
                (
                    "quote",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assets",
                        to="cpq.quote",
                    ),
                ),
                (
                    "quote_line",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="asset",
                        to="cpq.quoteline",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RuleCondition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("field_name", models.CharField(max_length=255)),
                (
                    "operator",
                    models.CharField(
                        choices=[
                            (">=", "Greater Than or Equal"),
                            ("<=", "Less Than or Equal"),
                            ("==", "Equal"),
                            (">", "Greater Than"),
                            ("<", "Less Than"),
                            ("!=", "Not Equal"),
                        ],
                        max_length=2,
                    ),
                ),
                ("value", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cpq.businessrule",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "billing_cycle",
                    models.CharField(
                        choices=[
                            ("Monthly", "Monthly"),
                            ("Quarterly", "Quarterly"),
                            ("Annually", "Annually"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "price_per_cycle",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("term", models.IntegerField()),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscriptions",
                        to="cpq.product",
                    ),
                ),
                (
                    "quote",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscriptions",
                        to="cpq.quote",
                    ),
                ),
                (
                    "quote_line",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscription",
                        to="cpq.quoteline",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Contract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "contract_status",
                    models.CharField(
                        choices=[
                            ("Active", "Active"),
                            ("Expired", "Expired"),
                            ("Renewed", "Renewed"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contract",
                        to="cpq.subscription",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SystemFieldMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "crm",
                    models.CharField(
                        choices=[
                            ("AgentCPQ", "AgentCPQ"),
                            ("Salesforce", "Salesforce"),
                            ("HubSpot", "HubSpot"),
                            ("Dynamics", "Microsoft Dynamics"),
                            ("Custom", "Custom CRM"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "field_type",
                    models.CharField(
                        choices=[
                            ("Opportunity", "Opportunity Field"),
                            ("Quote", "Quote Field"),
                            ("LineItem", "Line Item Field"),
                        ],
                        default="Quote",
                        max_length=50,
                    ),
                ),
                ("local_field", models.CharField(max_length=255)),
                ("crm_field", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "unique_together": {("crm", "field_type", "local_field", "crm_field")},
            },
        ),
        migrations.CreateModel(
            name="TenantUsageLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tenant_id", models.CharField(db_index=True, max_length=50)),
                ("billing_period", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[("success", "Success"), ("failure", "Failure")],
                        max_length=20,
                    ),
                ),
                ("http_status", models.IntegerField(blank=True, null=True)),
                (
                    "message",
                    models.TextField(
                        blank=True, help_text="Response body or error message"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["tenant_id", "billing_period", "status"],
                        name="cpq_tenantu_tenant__b75f5a_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Usage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("usage_date", models.DateField()),
                ("quantity_used", models.IntegerField()),
                ("cost_per_unit", models.DecimalField(decimal_places=2, max_digits=10)),
                ("total_cost", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usage_records",
                        to="cpq.product",
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usage_records",
                        to="cpq.subscription",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
<<<<<<< HEAD
            name="EmailAlertLog",
=======
            name='EmailAlertLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance_type', models.CharField(max_length=50)),
                ('instance_id', models.BigIntegerField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('email_alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cpq.emailalert')),
            ],
            options={
                'ordering': ['-sent_at'],
                'unique_together': {('email_alert', 'instance_type', 'instance_id')},
            },
        ),
        migrations.CreateModel(
            name='QuoteDocument',
>>>>>>> sympletech_sept_j
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("instance_type", models.CharField(max_length=50)),
                ("instance_id", models.BigIntegerField()),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                (
                    "email_alert",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="cpq.emailalert"
                    ),
                ),
            ],
            options={
                "ordering": ["-sent_at"],
                "unique_together": {("email_alert", "instance_type", "instance_id")},
            },
        ),
        migrations.CreateModel(
            name="QuoteDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.PositiveIntegerField()),
                ("name", models.CharField(max_length=255)),
                (
                    "content",
                    models.TextField(
                        blank=True,
                        help_text="Optional HTML/text content of the document",
                        null=True,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True, null=True, upload_to=cpq.models.temp_file_path
                    ),
                ),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "generated_by",
                    models.CharField(
                        blank=True,
                        help_text="Who generated this version (e.g., system, user email)",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "quote",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="cpq.quote",
                    ),
                ),
            ],
            options={
                "ordering": ["-version"],
                "unique_together": {("quote", "version")},
            },
        ),
        migrations.CreateModel(
            name="TenantUsageReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tenant_long_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "billing_period",
                    models.DateField(
                        help_text="First day of the month this report covers"
                    ),
                ),
                (
                    "total_actions",
                    models.PositiveBigIntegerField(
                        default=0,
                        help_text="Total number of actions performed by this tenant in the period",
                    ),
                ),
                (
                    "overflow_actions",
                    models.PositiveBigIntegerField(
                        default=0,
                        help_text="Number of actions beyond the tenant’s plan limit",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this report row was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this report row was last updated"
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usage_reports",
                        to="cpq.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["-billing_period"],
                "indexes": [
                    models.Index(
                        fields=["tenant", "billing_period"],
                        name="cpq_tenantu_tenant__9c77c3_idx",
                    )
                ],
                "unique_together": {("tenant", "billing_period")},
            },
        ),
    ]
