# Generated by Django 5.2.1 on 2025-07-16 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpq', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoteline',
            name='is_bundle_child',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='option',
            name='default_selected',
            field=models.BooleanField(default=True),
        ),
    ]
