# Generated by Django 5.1.5 on 2025-07-22 17:16

import cpq.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cpq", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="quoteline",
            name="is_bundle_child",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="tenant",
            name="api_key",
            field=models.CharField(
                default=cpq.models.gen_api_key,
                editable=False,
                help_text="Public API key, auto-generated",
                max_length=43,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="api_secret",
            field=models.CharField(
                default=cpq.models.gen_api_key,
                editable=False,
                help_text="Private key used for request signing",
                max_length=43,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="option",
            name="default_selected",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="quotedocument",
            name="file",
            field=models.FileField(
                blank=True, null=True, upload_to=cpq.models.temp_file_path
            ),
        ),
        migrations.AlterField(
            model_name="quoteline",
            name="parent_line",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="child_lines",
                to="cpq.quoteline",
            ),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="logo",
            field=models.ImageField(
                blank=True, null=True, upload_to=cpq.models.temp_logo_path
            ),
        ),
        migrations.CreateModel(
            name="TenantUsageLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tenant_id", models.CharField(db_index=True, max_length=50)),
                ("billing_period", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[("success", "Success"), ("failure", "Failure")],
                        max_length=20,
                    ),
                ),
                ("http_status", models.IntegerField(blank=True, null=True)),
                (
                    "message",
                    models.TextField(
                        blank=True, help_text="Response body or error message"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["tenant_id", "billing_period", "status"],
                        name="cpq_tenantu_tenant__b75f5a_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="TenantUsageReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tenant_long_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "billing_period",
                    models.DateField(
                        help_text="First day of the month this report covers"
                    ),
                ),
                (
                    "total_actions",
                    models.PositiveBigIntegerField(
                        default=0,
                        help_text="Total number of actions performed by this tenant in the period",
                    ),
                ),
                (
                    "overflow_actions",
                    models.PositiveBigIntegerField(
                        default=0,
                        help_text="Number of actions beyond the tenant’s plan limit",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this report row was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this report row was last updated"
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usage_reports",
                        to="cpq.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["-billing_period"],
                "indexes": [
                    models.Index(
                        fields=["tenant", "billing_period"],
                        name="cpq_tenantu_tenant__9c77c3_idx",
                    )
                ],
                "unique_together": {("tenant", "billing_period")},
            },
        ),
    ]
