# Generated by Django 5.1.5 on 2025-07-16 02:05

import cpq.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cpq", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="api_key",
            field=models.CharField(
                default=cpq.models.gen_api_key,
                editable=False,
                help_text="Public API key, auto-generated",
                max_length=43,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="api_secret",
            field=models.CharField(
                default=cpq.models.gen_api_key,
                editable=False,
                help_text="Private key used for request signing",
                max_length=43,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="TenantUsageReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "billing_period",
                    models.DateField(
                        help_text="First day of the month this report covers"
                    ),
                ),
                (
                    "total_actions",
                    models.PositiveBigIntegerField(
                        default=0,
                        help_text="Total number of actions performed by this tenant in the period",
                    ),
                ),
                (
                    "overflow_actions",
                    models.PositiveBigIntegerField(
                        default=0,
                        help_text="Number of actions beyond the tenant’s plan limit",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this report row was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this report row was last updated"
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usage_reports",
                        to="cpq.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["-billing_period"],
                "indexes": [
                    models.Index(
                        fields=["tenant", "billing_period"],
                        name="cpq_tenantu_tenant__9c77c3_idx",
                    )
                ],
                "unique_together": {("tenant", "billing_period")},
            },
        ),
    ]
