# Generated by Django 5.2.1 on 2025-10-06 21:32

from django.db import migrations, models


OLD_TABLE_NAME = "cpq_renewaltask"
NEW_TABLE_NAME = "cpq_scheduledtask"
OLD_INDEX_NAME = "cpq_renewal_status_8219f7_idx"
NEW_INDEX_NAME = "cpq_schedul_status_91de7c_idx"


def _table_exists(connection, table_name):
    with connection.cursor() as cursor:
        return table_name in set(connection.introspection.table_names(cursor))


def _rename_table(schema_editor, old_name, new_name):
    qn = schema_editor.quote_name
    if schema_editor.connection.vendor == "mysql":
        schema_editor.execute(f"RENAME TABLE {qn(old_name)} TO {qn(new_name)}")
    else:
        schema_editor.execute(
            f"ALTER TABLE {qn(old_name)} RENAME TO {qn(new_name)}"
        )


def _rename_index(schema_editor, table_name, old_name, new_name):
    connection = schema_editor.connection
    with connection.cursor() as cursor:
        constraints = connection.introspection.get_constraints(cursor, table_name)

    if old_name not in constraints or new_name in constraints:
        return

    qn = schema_editor.quote_name
    if schema_editor.connection.vendor == "mysql":
        schema_editor.execute(
            f"ALTER TABLE {qn(table_name)} RENAME INDEX {qn(old_name)} TO {qn(new_name)}"
        )
    else:
        schema_editor.execute(
            f"ALTER INDEX {qn(old_name)} RENAME TO {qn(new_name)}"
        )


def forwards(apps, schema_editor):
    connection = schema_editor.connection

    has_new = _table_exists(connection, NEW_TABLE_NAME)
    has_old = _table_exists(connection, OLD_TABLE_NAME)

    if not has_new and has_old:
        _rename_table(schema_editor, OLD_TABLE_NAME, NEW_TABLE_NAME)

    if _table_exists(connection, NEW_TABLE_NAME):
        _rename_index(schema_editor, NEW_TABLE_NAME, OLD_INDEX_NAME, NEW_INDEX_NAME)


def backwards(apps, schema_editor):
    connection = schema_editor.connection

    has_new = _table_exists(connection, NEW_TABLE_NAME)
    has_old = _table_exists(connection, OLD_TABLE_NAME)

    if not has_old and has_new:
        _rename_table(schema_editor, NEW_TABLE_NAME, OLD_TABLE_NAME)

    if _table_exists(connection, OLD_TABLE_NAME):
        _rename_index(schema_editor, OLD_TABLE_NAME, NEW_INDEX_NAME, OLD_INDEX_NAME)


class Migration(migrations.Migration):

    dependencies = [
        ('cpq', '0001_initial'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(forwards, backwards, elidable=True),
            ],
            state_operations=[
                migrations.RenameModel(
                    old_name='RenewalTask',
                    new_name='ScheduledTask',
                ),
                migrations.AlterModelOptions(
                    name='scheduledtask',
                    options={
                        'indexes': [
                            models.Index(
                                fields=['status', 'execute_at'],
                                name=NEW_INDEX_NAME,
                            )
                        ],
                        'verbose_name': 'Renewal Task',
                        'verbose_name_plural': 'Renewal Tasks',
                    },
                ),
            ],
        ),
    ]
