# Generated by Django 5.2.1 on 2025-07-08 19:44

import cpq.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpq', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteUIRender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_quote_name', models.BooleanField(default=True)),
                ('show_quote_status', models.BooleanField(default=True)),
                ('show_quote_account', models.BooleanField(default=True)),
                ('show_quote_opportunity', models.BooleanField(default=True)),
                ('show_quote_created_at', models.BooleanField(default=True)),
                ('show_quote_expires_at', models.BooleanField(default=True)),
                ('show_quote_discount', models.BooleanField(default=True)),
                ('rendered_fields', models.JSONField(blank=True, default=cpq.models.QuoteUIRender.default_rendered_fields)),
                ('omitted_fields', models.JSONField(blank=True, default=cpq.models.QuoteUIRender.default_omitted_fields)),
                ('show_quote_subtotal', models.BooleanField(default=True)),
                ('show_quote_net_amount', models.BooleanField(default=True)),
            ],
        ),
    ]
