# Generated by Django 5.1.5 on 2025-08-14 05:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cpq", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("recipient", models.EmailField(max_length=254)),
                ("subject", models.CharField(max_length=255)),
                ("template_name", models.CharField(max_length=100)),
                ("context", models.JSONField()),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name="customfield",
            name="options",
            field=models.JSONField(
                blank=True,
                help_text="Used for Dropdown data_type. List of options.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="customfieldvalue",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="customrecord",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_custom_records",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="customrecord",
            name="custom_identifier",
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="customrecord",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="customrecord",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="updated_custom_records",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="product",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="updated_products",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="quote",
            name="tax_percentage",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="quotedocumentsettings",
            name="quote_tax",
            field=models.DecimalField(decimal_places=2, default=7.25, max_digits=10),
        ),
        migrations.AddField(
            model_name="quotedocumentsettings",
            name="show_quote_tax_amount",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="quotedocumentsettings",
            name="show_quote_tax_information",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="quotedocumentsettings",
            name="show_quote_tax_percentage",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="customfield",
            name="custom_object",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="custom_fields",
                to="cpq.customobject",
            ),
        ),
        migrations.AlterField(
            model_name="customfieldvalue",
            name="record",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="custom_field_values",
                to="cpq.customrecord",
            ),
        ),
        migrations.AlterField(
            model_name="customrecord",
            name="object_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="records",
                to="cpq.customobject",
            ),
        ),
    ]
