# Generated by Django 5.1.5 on 2025-07-30 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cpq", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="quoteline",
            name="is_bundle_component_selected",
        ),
    ]
