# Generated by Django 5.2.1 on 2025-10-01 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpq', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='opportunity',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='cpq.opportunity'),
        ),
    ]
