# Generated by Django 5.1.5 on 2025-07-04 17:12

from django.db import migrations, models




class Migration(migrations.Migration):

    dependencies = [
        ("cpq", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='street',
            field=models.CharField(max_length=255, null=True, blank=True),
        ),
        migrations.AddField(
            model_name='account',
            name='state',
            field=models.CharField(max_length=100, null=True, blank=True),
        ),
        migrations.AddField(
            model_name='account',
            name='zip_code',
            field=models.CharField(max_length=20, null=True, blank=True),
        ),
    ]
