# Generated by Django 5.1.5 on 2025-07-22 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cpq", "0002_account_tenant_id_quoteline_is_bundle_child_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="account",
            name="tenant_id",
        ),
    ]
