# Generated by Django 5.1.5 on 2025-07-06 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cpq", "0002_add_missing_address_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customfieldvalue",
            name="record",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="cpq.customrecord",
            ),
        ),
        migrations.AlterField(
            model_name="customrecord",
            name="record_id",
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
