# Generated by Django 5.1.5 on 2025-07-16 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cpq", "0002_tenant_api_key_tenant_api_secret_tenantusagereport"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="tenant_id",
            field=models.CharField(default=2121212121, max_length=30, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tenantusagereport",
            name="tenant_long_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
