# Generated by Django 5.1.5 on 2025-10-13 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cpq", "0002_rename_renewaltask_scheduledtask_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="quickbooks_customer_id",
            field=models.CharField(
                blank=True,
                help_text="Identifier of the Customer in QuickBooks",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="quote",
            name="quickbooks_invoice_id",
            field=models.CharField(
                blank=True,
                help_text="Identifier of the Invoice created in QuickBooks",
                max_length=100,
                null=True,
            ),
        ),
    ]
