# Generated by Django 5.2.1 on 2025-10-01 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpq', '0002_contract_opportunity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='opportunity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='cpq.opportunity'),
        ),
    ]
