# Generated by Django 5.2.4 on 2025-07-17 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpq', '0002_quoteline_is_bundle_child_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quoteline',
            name='parent_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_lines', to='cpq.quoteline'),
        ),
    ]
