# Generated by Django 5.1.5 on 2025-07-30 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cpq", "0002_remove_quoteline_is_bundle_component_selected"),
    ]

    operations = [
        migrations.AddField(
            model_name="quoteline",
            name="is_bundle_component_selected",
            field=models.BooleanField(default=False),
        ),
    ]
