# Generated by Django 5.2.1 on 2025-07-08 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cpq', '0002_quoteuirender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quoteuirender',
            name='show_quote_name',
        ),
        migrations.RemoveField(
            model_name='quoteuirender',
            name='show_quote_status',
        ),
    ]
