# Generated by Django 5.1.5 on 2025-07-06 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cpq", "0003_alter_customfieldvalue_record_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customfieldvalue",
            name="object_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
