# Generated by Django 5.1.5 on 2025-07-16 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cpq", "0003_account_tenant_id_tenantusagereport_tenant_long_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="TenantUsageLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tenant_id", models.CharField(db_index=True, max_length=50)),
                ("billing_period", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[("success", "Success"), ("failure", "Failure")],
                        max_length=20,
                    ),
                ),
                ("http_status", models.IntegerField(blank=True, null=True)),
                (
                    "message",
                    models.TextField(
                        blank=True, help_text="Response body or error message"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["tenant_id", "billing_period", "status"],
                        name="cpq_tenantu_tenant__b75f5a_idx",
                    )
                ],
            },
        ),
    ]
