# Generated by Django 5.2.1 on 2025-07-18 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpq', '0003_alter_quoteline_parent_line'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoteline',
            name='is_bundle_component_selected',
            field=models.BooleanField(default=False),
        ),
    ]
