# Generated by Django 5.1.5 on 2025-10-14 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cpq", "0003_account_quickbooks_customer_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="quote",
            name="quickbooks_invoice_number",
            field=models.CharField(
                blank=True,
                help_text="QuickBooks customer-facing invoice number (DocNumber)",
                max_length=100,
                null=True,
            ),
        ),
    ]
