# Generated by Django 5.2.1 on 2025-10-01 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpq', '0003_alter_contract_opportunity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='subscription',
        ),
        migrations.AddField(
            model_name='subscription',
            name='contract',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='cpq.contract'),
            preserve_default=False,
        ),
    ]
