# Generated by Django 5.1.5 on 2025-07-30 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cpq", "0003_quoteline_is_bundle_component_selected"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customfield",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="customfield",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="customfield",
            name="updated_by",
        ),
        migrations.RemoveField(
            model_name="customobject",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="customobject",
            name="updated_by",
        ),
    ]
