# Generated by Django 5.1.5 on 2025-07-22 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cpq", "0003_remove_account_tenant_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="tenant_id",
            field=models.CharField(max_length=30, null=True, unique=True),
        ),
    ]
