# Generated by Django 5.2.4 on 2025-07-10 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpq', '0003_remove_quoteuirender_show_quote_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quoteline',
            name='discount_type',
            field=models.CharField(blank=True, choices=[('percentage', 'Percentage'), ('amount', 'Amount')], default='percentage', max_length=20, null=True),
        ),
    ]
