# Generated by Django 5.1.5 on 2025-07-22 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cpq", "0004_account_tenant_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="account",
            name="tenant_id",
        ),
    ]
