# Generated by Django 5.2.1 on 2025-10-01 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpq', '0004_remove_contract_subscription_subscription_contract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
