# Generated by Django 5.2.4 on 2025-09-18 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpq', '0004_alter_activity_created_at_alter_lead_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customfieldvalue',
            name='value',
            field=models.TextField(blank=True),
        ),
    ]
