# Generated by Django 5.1.5 on 2025-10-06 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cpq", "0004_knowledge"),
    ]

    operations = [
        migrations.AlterField(
            model_name="knowledge",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
