# Generated by Django 5.1.5 on 2025-07-12 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cpq", "0005_account_created_by_activity_activityid_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="account",
            name="street",
        ),
    ]
