# Generated by Django 5.1.5 on 2025-07-30 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cpq", "0005_customfield_created_by_customfield_updated_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customobject",
            name="created_at",
        ),
    ]
