# Generated by Django 5.2.1 on 2025-10-01 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpq', '0005_alter_contract_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='billing_cycle',
            field=models.CharField(choices=[('monthly', 'monthly'), ('quarterly', 'quarterly'), ('annual', 'annual'), ('one_time', 'one_time')], default='monthly', max_length=50),
        ),
    ]
