# Generated by Django 5.1.5 on 2025-10-19 19:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cpq", "0005_quotependingattachment"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="customfieldvalue",
            name="updated_by_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="updated_custom_field_values",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="emailalert",
            name="native_object",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Lead", "Lead"),
                    ("Account", "Account"),
                    ("Opportunity", "Opportunity"),
                    ("Quote", "Quote"),
                    ("Subscription", "Subscription"),
                    ("Product", "Product"),
                    ("QuoteLine", "Quote Line"),
                    ("User", "User"),
                    ("Contract", "Contract"),
                    ("Contact", "Contact"),
                    ("Activity", "Activity"),
                ],
                help_text="Select a native object",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="emailalert",
            name="trigger",
            field=models.CharField(
                choices=[
                    ("lead_created", "New Lead Created"),
                    ("account_created", "New Account Created"),
                    ("opportunity_created", "New Opportunity Created"),
                    ("opportunity_closed_won", "Opportunity Closed Won"),
                    ("opportunity_closed_lost", "Opportunity Closed Lost"),
                    ("quote_sent_for_approval", "Quote Sent for Approval"),
                    ("quote_approved", "Quote Approved"),
                    ("quote_rejected", "Quote Rejected"),
                    ("quote_expiring", "Quote Expiring Soon"),
                    ("subscription_renewal", "Subscription Renewal Reminder"),
                    ("user_created", "New User Created"),
                    ("opportunity_greater_than_10k", "Opportunity Amount > $10K"),
                    ("quote_discount_greater_than_50", "Quote Discount > 50%"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="quotedocumentsettings",
            name="quote_tax",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
