# Generated by Django 5.1.5 on 2025-11-25 01:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def create_actionlog_table_if_missing(apps, schema_editor):
    """
    Safely create the cpq_actionlog table only if it doesn't already exist.
    This prevents migrations from failing on environments where the table was
    created manually or by earlier schema changes.
    """
    table_name = "cpq_actionlog"
    if table_name in schema_editor.connection.introspection.table_names():
        return

    class TempActionLog(models.Model):
        id = models.BigAutoField(
            auto_created=True,
            primary_key=True,
            serialize=False,
            verbose_name="ID",
        )
        trigger_name = models.CharField(max_length=255)
        operation = models.CharField(
            choices=[
                ("CREATE", "Create"),
                ("UPDATE", "Update"),
                ("DELETE", "Delete"),
            ],
            max_length=20,
        )
        target_model = models.CharField(max_length=255)
        target_pk = models.CharField(max_length=100, null=True, blank=True)
        event_type = models.CharField(
            max_length=100,
            blank=True,
            null=True,
            help_text="Event type that fired the trigger (e.g., quote_line.update)",
        )
        signal_timing = models.CharField(
            choices=[
                ("pre_save", "Before Save"),
                ("post_save", "After Save"),
                ("pre_delete", "Before Delete"),
                ("post_delete", "After Delete"),
            ],
            default="post_save",
            help_text="Indicates whether this action was triggered pre/post save/delete.",
            max_length=20,
        )
        payload = models.JSONField(default=dict, blank=True)
        result = models.JSONField(default=dict, blank=True)
        status = models.CharField(
            choices=[
                ("pending", "Pending"),
                ("success", "Success"),
                ("failed", "Failed"),
            ],
            default="pending",
            max_length=20,
        )
        executed_at = models.DateTimeField(default=django.utils.timezone.now)

        class Meta:
            app_label = "cpq"
            db_table = table_name
            managed = False

    schema_editor.create_model(TempActionLog)


def drop_actiontrigger_legacy_columns(apps, schema_editor):
    """
    Safely drop legacy ActionTrigger columns only if they still exist.
    Prevents migration failures on environments where columns were removed manually.
    """
    def drop_column_if_exists(table_name, column_name):
        with schema_editor.connection.cursor() as cursor:
            cursor.execute(
                """
                SELECT COUNT(*)
                FROM information_schema.columns
                WHERE table_schema = DATABASE()
                  AND table_name = %s
                  AND column_name = %s
                """,
                [table_name, column_name],
            )
            if cursor.fetchone()[0]:
                cursor.execute(
                    f"ALTER TABLE `{table_name}` DROP COLUMN `{column_name}`"
                )

    for col in ["action", "action_params", "object_name", "trigger"]:
        drop_column_if_exists("cpq_actiontrigger", col)


def add_actiontrigger_field_if_missing(apps, schema_editor, field_name, field):
    """
    Generic helper to add a column to cpq_actiontrigger only if it doesn't exist.
    """
    ActionTrigger = apps.get_model("cpq", "ActionTrigger")
    table_name = ActionTrigger._meta.db_table

    # Safety: some environments may have migration history marked as applied
    # while the underlying table was never created. Ensure the table exists
    # before checking/adding columns.
    if table_name not in schema_editor.connection.introspection.table_names():
        schema_editor.create_model(ActionTrigger)

    # Ensure the field has name/column metadata before we inspect the DB
    field.set_attributes_from_name(field_name)
    column_name = field.column

    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            """
            SELECT COUNT(*)
            FROM information_schema.columns
            WHERE table_schema = DATABASE()
              AND table_name = %s
              AND column_name = %s
            """,
            [table_name, column_name],
        )
        if cursor.fetchone()[0]:
            return

    schema_editor.add_field(ActionTrigger, field)


def add_actions_column_if_missing(apps, schema_editor):
    """
    Add the `actions` column to cpq_actiontrigger only if it's absent.
    Avoids duplicate-column errors on databases that already have it.
    """
    add_actiontrigger_field_if_missing(
        apps,
        schema_editor,
        "actions",
        models.JSONField(
            default=dict,
            help_text="List of actions to execute if conditions are met.",
        ),
    )


def add_conditions_column_if_missing(apps, schema_editor):
    """
    Add the `conditions` column to cpq_actiontrigger only if it's absent.
    Prevents duplicate-column errors on databases that already have it.
    """
    add_actiontrigger_field_if_missing(
        apps,
        schema_editor,
        "conditions",
        models.JSONField(
            blank=True,
            null=True,
            help_text="Logical structure for evaluating conditions (with AND/OR, items, etc.)",
        ),
    )


def add_created_by_column_if_missing(apps, schema_editor):
    # Resolve the user model from historical state to avoid lookup errors
    app_label, model_name = settings.AUTH_USER_MODEL.split(".")
    UserModel = apps.get_model(app_label, model_name)
    add_actiontrigger_field_if_missing(
        apps,
        schema_editor,
        "created_by",
        models.ForeignKey(
            UserModel,
            on_delete=django.db.models.deletion.SET_NULL,
            null=True,
            blank=True,
            related_name="created_action_triggers",
        ),
    )


def add_description_column_if_missing(apps, schema_editor):
    add_actiontrigger_field_if_missing(
        apps,
        schema_editor,
        "description",
        models.TextField(blank=True, null=True),
    )


def add_event_type_column_if_missing(apps, schema_editor):
    add_actiontrigger_field_if_missing(
        apps,
        schema_editor,
        "event_type",
        models.JSONField(blank=True, null=True),
    )


def add_name_column_if_missing(apps, schema_editor):
    add_actiontrigger_field_if_missing(
        apps,
        schema_editor,
        "name",
        models.CharField(max_length=255, unique=True, default="Unnamed Trigger"),
    )


def add_priority_column_if_missing(apps, schema_editor):
    add_actiontrigger_field_if_missing(
        apps,
        schema_editor,
        "priority",
        models.IntegerField(
            default=100,
            help_text="Lower number = higher priority. Triggers run in ascending priority order.",
        ),
    )


def add_signal_timing_column_if_missing(apps, schema_editor):
    add_actiontrigger_field_if_missing(
        apps,
        schema_editor,
        "signal_timing",
        models.CharField(
            choices=[
                ("pre_save", "Before Save"),
                ("post_save", "After Save"),
                ("pre_delete", "Before Delete"),
                ("post_delete", "After Delete"),
            ],
            default="post_save",
            help_text="Defines whether the trigger runs before or after saving/deleting.",
            max_length=20,
        ),
    )


def add_updated_at_column_if_missing(apps, schema_editor):
    add_actiontrigger_field_if_missing(
        apps,
        schema_editor,
        "updated_at",
        models.DateTimeField(auto_now=True),
    )


class Migration(migrations.Migration):
    # This migration includes defensive DDL in RunPython operations (creating
    # tables when migration history is inconsistent). MySQL forbids DDL inside
    # a transaction when it can't be rolled back, so disable atomicity.
    atomic = False

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("cpq", "0006_customfieldvalue_updated_by_user_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    create_actionlog_table_if_missing,
                    reverse_code=migrations.RunPython.noop,
                )
            ],
            state_operations=[
                migrations.CreateModel(
                    name="ActionLog",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        ("trigger_name", models.CharField(max_length=255)),
                        (
                            "operation",
                            models.CharField(
                                choices=[
                                    ("CREATE", "Create"),
                                    ("UPDATE", "Update"),
                                    ("DELETE", "Delete"),
                                ],
                                max_length=20,
                            ),
                        ),
                        (
                            "target_model",
                            models.CharField(max_length=255),
                        ),
                        (
                            "target_pk",
                            models.CharField(blank=True, max_length=100, null=True),
                        ),
                        (
                            "event_type",
                            models.CharField(
                                blank=True,
                                help_text="Event type that fired the trigger (e.g., quote_line.update)",
                                max_length=100,
                                null=True,
                            ),
                        ),
                        (
                            "signal_timing",
                            models.CharField(
                                choices=[
                                    ("pre_save", "Before Save"),
                                    ("post_save", "After Save"),
                                    ("pre_delete", "Before Delete"),
                                    ("post_delete", "After Delete"),
                                ],
                                default="post_save",
                                help_text="Indicates whether this action was triggered pre/post save/delete.",
                                max_length=20,
                            ),
                        ),
                        ("payload", models.JSONField(blank=True, default=dict)),
                        ("result", models.JSONField(blank=True, default=dict)),
                        (
                            "status",
                            models.CharField(
                                choices=[
                                    ("pending", "Pending"),
                                    ("success", "Success"),
                                    ("failed", "Failed"),
                                ],
                                default="pending",
                                max_length=20,
                            ),
                        ),
                        (
                            "executed_at",
                            models.DateTimeField(default=django.utils.timezone.now),
                        ),
                    ],
                    options={
                        "verbose_name": "Action Log",
                        "verbose_name_plural": "Action Logs",
                        "ordering": ["-executed_at"],
                    },
                )
            ],
        ),
        migrations.AlterModelOptions(
            name="actiontrigger",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Action Trigger",
                "verbose_name_plural": "Action Triggers",
            },
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    drop_actiontrigger_legacy_columns,
                    reverse_code=migrations.RunPython.noop,
                )
            ],
            state_operations=[
                migrations.RemoveField(
                    model_name="actiontrigger",
                    name="action",
                ),
                migrations.RemoveField(
                    model_name="actiontrigger",
                    name="action_params",
                ),
                migrations.RemoveField(
                    model_name="actiontrigger",
                    name="object_name",
                ),
                migrations.RemoveField(
                    model_name="actiontrigger",
                    name="trigger",
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    add_actions_column_if_missing,
                    reverse_code=migrations.RunPython.noop,
                )
            ],
            state_operations=[
                migrations.AddField(
                    model_name="actiontrigger",
                    name="actions",
                    field=models.JSONField(
                        default=dict,
                        help_text="List of actions to execute if conditions are met.",
                    ),
                )
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    add_conditions_column_if_missing,
                    reverse_code=migrations.RunPython.noop,
                )
            ],
            state_operations=[
                migrations.AddField(
                    model_name="actiontrigger",
                    name="conditions",
                    field=models.JSONField(
                        blank=True,
                        help_text="Logical structure for evaluating conditions (with AND/OR, items, etc.)",
                        null=True,
                    ),
                )
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    add_created_by_column_if_missing,
                    reverse_code=migrations.RunPython.noop,
                )
            ],
            state_operations=[
                migrations.AddField(
                    model_name="actiontrigger",
                    name="created_by",
                    field=models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_action_triggers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    add_description_column_if_missing,
                    reverse_code=migrations.RunPython.noop,
                )
            ],
            state_operations=[
                migrations.AddField(
                    model_name="actiontrigger",
                    name="description",
                    field=models.TextField(blank=True, null=True),
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    add_event_type_column_if_missing,
                    reverse_code=migrations.RunPython.noop,
                )
            ],
            state_operations=[
                migrations.AddField(
                    model_name="actiontrigger",
                    name="event_type",
                    field=models.JSONField(blank=True, null=True),
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    add_name_column_if_missing,
                    reverse_code=migrations.RunPython.noop,
                )
            ],
            state_operations=[
                migrations.AddField(
                    model_name="actiontrigger",
                    name="name",
                    field=models.CharField(
                        default="Unnamed Trigger", max_length=255, unique=True
                    ),
                    preserve_default=False,
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    add_priority_column_if_missing,
                    reverse_code=migrations.RunPython.noop,
                )
            ],
            state_operations=[
                migrations.AddField(
                    model_name="actiontrigger",
                    name="priority",
                    field=models.IntegerField(
                        default=100,
                        help_text="Lower number = higher priority. Triggers run in ascending priority order.",
                    ),
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    add_signal_timing_column_if_missing,
                    reverse_code=migrations.RunPython.noop,
                )
            ],
            state_operations=[
                migrations.AddField(
                    model_name="actiontrigger",
                    name="signal_timing",
                    field=models.CharField(
                        choices=[
                            ("pre_save", "Before Save"),
                            ("post_save", "After Save"),
                            ("pre_delete", "Before Delete"),
                            ("post_delete", "After Delete"),
                        ],
                        default="post_save",
                        help_text="Defines whether the trigger runs before or after saving/deleting.",
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    add_updated_at_column_if_missing,
                    reverse_code=migrations.RunPython.noop,
                )
            ],
            state_operations=[
                migrations.AddField(
                    model_name="actiontrigger",
                    name="updated_at",
                    field=models.DateTimeField(auto_now=True),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="actiontrigger",
            name="active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="actiontrigger",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name="CustomAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("CREATE", "Create"),
                            ("UPDATE", "Update"),
                            ("DELETE", "Delete"),
                        ],
                        max_length=10,
                    ),
                ),
                ("target_lookup", models.JSONField(blank=True, null=True)),
                ("data", models.JSONField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_custom_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "target_content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Custom Action",
                "verbose_name_plural": "Custom Actions",
                "ordering": ["-created_at"],
            },
        ),
    ]
