# Generated by Django 5.1.5 on 2025-07-30 04:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cpq", "0006_remove_customobject_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="customobject",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
