# Generated by Django 5.2.1 on 2025-10-03 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpq', '0006_alter_subscription_billing_cycle'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionTrigger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger', models.CharField(choices=[('opportunity_closed_won', 'Opportunity Closed Won')], help_text='Select the event that will trigger the action.', max_length=100, verbose_name='Trigger (event)')),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete')], help_text='Select the action to perform: Create, Update, or Delete.', max_length=20, verbose_name='Action')),
                ('object_name', models.CharField(choices=[('renewal_task', 'Renewal Task')], help_text='Select the object on which the action will be performed.', max_length=50, verbose_name='Object')),
                ('action_params', models.JSONField(blank=True, default=dict, help_text='Optional. JSON with parameters for the action/function.', verbose_name='Action Parameters')),
                ('active', models.BooleanField(default=True, help_text='Indicates whether the trigger is active and will execute when the event occurs.', verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when this record was created (read-only).', verbose_name='Created At')),
            ],
        ),
        migrations.CreateModel(
            name='RenewalTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('execute_at', models.DateTimeField(help_text='The date and time when this renewal task should be executed.', verbose_name='Execution Date')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('done', 'Done'), ('failed', 'Failed')], default='pending', help_text='Current status of the renewal task: Pending, Done, or Failed.', max_length=20, verbose_name='Status')),
                ('attempts', models.IntegerField(default=0, help_text='Number of times this task has been attempted.', verbose_name='Attempts')),
                ('last_error', models.TextField(blank=True, help_text='If the task failed, this field stores the last error message.', null=True, verbose_name='Last Error')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when this task was created (read-only).', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time when this task was last updated (read-only).', verbose_name='Updated At')),
                ('opportunity', models.ForeignKey(help_text='The Opportunity associated with this renewal task.', on_delete=django.db.models.deletion.CASCADE, related_name='renewal_tasks', to='cpq.opportunity', verbose_name='Opportunity')),
            ],
            options={
                'verbose_name': 'Renewal Task',
                'verbose_name_plural': 'Renewal Tasks',
                'indexes': [models.Index(fields=['status', 'execute_at'], name='cpq_renewal_status_8219f7_idx')],
            },
        ),
    ]
