# Generated by Django 5.1.5 on 2025-07-12 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cpq", "0006_remove_account_street"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="street",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
