# Generated by Django 5.1.5 on 2025-07-12 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cpq", "0007_account_street"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="account",
            name="city",
        ),
        migrations.RemoveField(
            model_name="account",
            name="state",
        ),
        migrations.RemoveField(
            model_name="account",
            name="zip_code",
        ),
    ]
