# Generated by Django 5.2.1 on 2025-10-06 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cpq', '0007_actiontrigger_renewaltask'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RenewalTask',
            new_name='ScheduledTask',
        ),
        migrations.RenameIndex(
            model_name='scheduledtask',
            new_name='cpq_schedul_status_91de7c_idx',
            old_name='cpq_renewal_status_8219f7_idx',
        ),
    ]
