# Generated by Django 5.2.1 on 2025-07-28 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpq', '0007_customfield_created_by_customfield_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='tax_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='quotedocumentsettings',
            name='quote_tax_percentaje',
            field=models.DecimalField(decimal_places=2, default=7.25, max_digits=10),
        ),
        migrations.AddField(
            model_name='quotedocumentsettings',
            name='show_quote_tax_percentaje',
            field=models.BooleanField(default=True),
        ),
    ]
