# Generated by Django 5.1.5 on 2025-12-09 15:54

import cpq.models
import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cpq", "0008_product_price_mode_fixed_price"),
    ]

    operations = [
        migrations.CreateModel(
            name="OpportunityStage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=50, unique=True)),
                ("label", models.CharField(max_length=100)),
                ("active", models.BooleanField(default=True)),
                ("sort_order", models.IntegerField(default=0)),
                ("is_default", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Opportunity Stage",
                "verbose_name_plural": "Opportunity Stages",
            },
        ),
        migrations.AlterField(
            model_name="opportunity",
            name="stage",
            field=models.CharField(
                default=cpq.models.default_opportunity_stage, max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="fixed_price",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
        migrations.CreateModel(
            name="PicklistValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_name", models.CharField(max_length=100)),
                ("field_name", models.CharField(max_length=100)),
                ("key", models.CharField(max_length=100)),
                ("label", models.CharField(max_length=255)),
                ("active", models.BooleanField(default=True)),
                ("sort_order", models.IntegerField(default=0)),
                ("is_default", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Picklist Value",
                "verbose_name_plural": "Picklist Values",
                "unique_together": {("object_name", "field_name", "key")},
            },
        ),
    ]
