# Generated by Django 5.1.5 on 2025-07-12 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cpq", "0008_remove_account_city_remove_account_state_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="city",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="account",
            name="state",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="account",
            name="zip_code",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
