# Generated by Django 5.2.1 on 2025-07-28 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpq', '0008_quote_tax_percentage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotedocumentsettings',
            name='show_quote_tax_percentaje',
        ),
        migrations.AddField(
            model_name='quotedocumentsettings',
            name='show_quote_tax_percentage',
            field=models.BooleanField(default=True),
        ),
    ]
