# Generated by Django 5.2.1 on 2025-07-28 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cpq', '0009_remove_quotedocumentsettings_show_quote_tax_percentaje_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quotedocumentsettings',
            old_name='quote_tax_percentaje',
            new_name='quote_tax_percentage',
        ),
    ]
