# Generated by Django 5.1.5 on 2025-07-12 17:52
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ("cpq", "0009_account_city_account_state_account_zip_code"),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(max_length=100)),
                ('action_date', models.DateField()),
                ('count', models.PositiveIntegerField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cpq.account')),
            ],
        ),
    ]
