# Generated by Django 5.2.1 on 2025-07-28 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpq', '0010_rename_quote_tax_percentaje_quotedocumentsettings_quote_tax_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotedocumentsettings',
            name='show_quote_tax_amount',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='quotedocumentsettings',
            name='show_quote_tax_inform',
            field=models.BooleanField(default=True),
        ),
    ]
