# Generated by Django 5.1.5 on 2025-07-12 18:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cpq", "0010_recreate_actionusage"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="actionusage",
            options={"ordering": ["-timestamp"]},
        ),
        migrations.RenameField(
            model_name="actionusage",
            old_name="action_type",
            new_name="action",
        ),
        migrations.RemoveField(
            model_name="actionusage",
            name="account",
        ),
        migrations.RemoveField(
            model_name="actionusage",
            name="action_date",
        ),
        migrations.RemoveField(
            model_name="actionusage",
            name="count",
        ),
        migrations.AddField(
            model_name="actionusage",
            name="related_object_id",
            field=models.CharField(
                blank=True,
                help_text="ID of the related object (e.g., Q-0001, PROD-001)",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="actionusage",
            name="related_object_type",
            field=models.CharField(
                blank=True,
                help_text="Type of object this action is related to (e.g., Quote, Product, Approval)",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="actionusage",
            name="timestamp",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="actionusage",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="action_usages",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
