# Generated by Django 5.2.1 on 2025-07-28 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cpq', '0011_quotedocumentsettings_show_quote_tax_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quotedocumentsettings',
            old_name='show_quote_tax_inform',
            new_name='show_quote_tax_information',
        ),
    ]
