# Generated by Django 5.1.5 on 2025-07-12 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cpq", "0011_alter_actionusage_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="businessrule",
            name="description",
        ),
    ]
