# Generated by Django 5.2.1 on 2025-07-29 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cpq', '0012_rename_show_quote_tax_inform_quotedocumentsettings_show_quote_tax_information'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quotedocumentsettings',
            old_name='quote_tax_percentage',
            new_name='quote_tax',
        ),
    ]
