# Generated by Django 5.1.5 on 2025-07-12 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cpq", "0012_remove_businessrule_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="businessrule",
            name="description",
            field=models.CharField(default="fasdfasdfasdf", max_length=255),
            preserve_default=False,
        ),
    ]
