# Generated by Django 5.1.5 on 2025-12-27 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cpq", "0013_tenant_sidebar_theme"),
    ]

    operations = [
        migrations.AlterField(
            model_name="actionlog",
            name="operation",
            field=models.CharField(
                choices=[
                    ("CREATE", "Create"),
                    ("UPDATE", "Update"),
                    ("DELETE", "Delete"),
                    ("CLONE", "Clone"),
                    ("EMAIL", "Email"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="actiontrigger",
            name="signal_timing",
            field=models.CharField(
                choices=[
                    ("pre_save", "Before Save"),
                    ("post_save", "After Save"),
                    ("pre_delete", "Before Delete"),
                    ("post_delete", "After Delete"),
                    ("virtual", "Virtual"),
                ],
                default="post_save",
                help_text="Defines whether the trigger runs before or after saving/deleting.",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="customrecord",
            name="custom_identifier",
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="quote",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
