# Generated by Django 5.1.5 on 2025-07-13 22:42

import cpq.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cpq", "0013_businessrule_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quotedocument",
            name="file",
            field=models.FileField(
                blank=True, null=True, upload_to=cpq.models.temp_file_path
            ),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="logo",
            field=models.ImageField(
                blank=True, null=True, upload_to=cpq.models.temp_logo_path
            ),
        ),
    ]
