# Generated by Django 5.2.4 on 2025-07-29 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cpq', '0013_rename_quote_tax_percentage_quotedocumentsettings_quote_tax'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='tax_amount',
        ),
    ]
