# Generated by Django 5.1.5 on 2025-12-27

from django.db import migrations


def _column_exists(connection, table_name, column_name):
    with connection.cursor() as cursor:
        try:
            columns = connection.introspection.get_table_description(cursor, table_name)
        except Exception:
            return False
    return any(c.name == column_name for c in columns)


def add_quote_quickbooks_fields_if_missing(apps, schema_editor):
    Quote = apps.get_model("cpq", "Quote")
    table_name = Quote._meta.db_table

    # Safety: if the table is missing entirely (inconsistent migration history),
    # create it from the historical model state.
    if table_name not in schema_editor.connection.introspection.table_names():
        schema_editor.create_model(Quote)
        return

    def add_field_if_missing(field_name: str) -> None:
        field = Quote._meta.get_field(field_name)
        column_name = field.column

        if _column_exists(schema_editor.connection, table_name, column_name):
            return

        schema_editor.add_field(Quote, field)

    add_field_if_missing("quickbooks_invoice_id")
    add_field_if_missing("quickbooks_invoice_number")


class Migration(migrations.Migration):
    # MySQL forbids DDL inside a transaction when it can't be rolled back.
    atomic = False

    dependencies = [
        ("cpq", "0014_alter_actionlog_operation_and_more"),
    ]

    operations = [
        migrations.RunPython(
            add_quote_quickbooks_fields_if_missing,
            reverse_code=migrations.RunPython.noop,
        ),
    ]

