# Generated by Django 5.2.4 on 2025-07-29 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpq', '0014_remove_quote_tax_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
