# Generated by Django 5.1.5 on 2025-12-27

from django.db import migrations


def add_account_quickbooks_customer_id_if_missing(apps, schema_editor):
    Account = apps.get_model("cpq", "Account")
    table_name = Account._meta.db_table

    # Safety: if the table is missing entirely (inconsistent migration history),
    # create it from the historical model state.
    if table_name not in schema_editor.connection.introspection.table_names():
        schema_editor.create_model(Account)
        return

    field = Account._meta.get_field("quickbooks_customer_id")
    column_name = field.column

    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            """
            SELECT COUNT(*)
            FROM information_schema.columns
            WHERE table_schema = DATABASE()
              AND table_name = %s
              AND column_name = %s
            """,
            [table_name, column_name],
        )
        if cursor.fetchone()[0]:
            return

    schema_editor.add_field(Account, field)


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("cpq", "0015_quote_quickbooks_invoice_fields"),
    ]

    operations = [
        migrations.RunPython(
            add_account_quickbooks_customer_id_if_missing,
            reverse_code=migrations.RunPython.noop,
        ),
    ]

