# Generated by Django 5.1.5 on 2025-12-27

from django.db import migrations


def _column_exists(connection, table_name, column_name):
    with connection.cursor() as cursor:
        try:
            columns = connection.introspection.get_table_description(cursor, table_name)
        except Exception:
            return False
    return any(c.name == column_name for c in columns)


def add_businessrule_created_by_if_missing(apps, schema_editor):
    BusinessRule = apps.get_model("cpq", "BusinessRule")
    table_name = BusinessRule._meta.db_table

    # The table exists in prod (we're missing only the column), but be defensive.
    if table_name not in schema_editor.connection.introspection.table_names():
        schema_editor.create_model(BusinessRule)
        return

    field = BusinessRule._meta.get_field("created_by")
    column_name = field.column

    if _column_exists(schema_editor.connection, table_name, column_name):
        return

    schema_editor.add_field(BusinessRule, field)


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("cpq", "0016_account_quickbooks_customer_field"),
    ]

    operations = [
        migrations.RunPython(
            add_businessrule_created_by_if_missing,
            reverse_code=migrations.RunPython.noop,
        ),
    ]

