# Generated by Django 5.2.1 on 2025-08-06 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpq', '0017_emailnotification_customrecord_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customfield',
            name='options',
            field=models.JSONField(blank=True, help_text='Used for Dropdown data_type. List of options.', null=True),
        ),
    ]
