# Generated by Django 5.1.5 on 2025-12-27

import django.db.models.deletion
from django.db import migrations, models


def _column_exists(connection, table_name, column_name):
    with connection.cursor() as cursor:
        try:
            columns = connection.introspection.get_table_description(cursor, table_name)
        except Exception:
            return False
    return any(c.name == column_name for c in columns)


def ensure_subscription_contract_column(apps, schema_editor):
    Contract = apps.get_model("cpq", "Contract")
    Subscription = apps.get_model("cpq", "Subscription")

    contract_table = Contract._meta.db_table
    subscription_table = Subscription._meta.db_table

    existing_tables = set(schema_editor.connection.introspection.table_names())

    # Safety: handle inconsistent migration history / missing tables.
    if contract_table not in existing_tables:
        schema_editor.create_model(Contract)
        existing_tables.add(contract_table)

    if subscription_table not in existing_tables:
        schema_editor.create_model(Subscription)
        return

    # If the column already exists, nothing to do.
    contract_field = Subscription._meta.get_field("contract")
    contract_column = contract_field.column
    if _column_exists(schema_editor.connection, subscription_table, contract_column):
        return

    # Add as nullable to avoid failures when historical rows exist.
    field = models.ForeignKey(
        Contract,
        on_delete=django.db.models.deletion.CASCADE,
        related_name="subscriptions",
        null=True,
        blank=True,
    )
    field.set_attributes_from_name("contract")
    schema_editor.add_field(Subscription, field)


class Migration(migrations.Migration):
    # MySQL forbids DDL inside a transaction when it can't be rolled back.
    atomic = False

    dependencies = [
        ("cpq", "0017_businessrule_created_by_field"),
    ]

    operations = [
        migrations.RunPython(ensure_subscription_contract_column, migrations.RunPython.noop),
    ]
