# Generated by Django 5.1.5 on 2025-12-27

import django.db.models.deletion
from django.db import migrations, models


def _column_exists(connection, table_name, column_name):
    with connection.cursor() as cursor:
        try:
            columns = connection.introspection.get_table_description(cursor, table_name)
        except Exception:
            return False
    return any(c.name == column_name for c in columns)


def ensure_contract_opportunity_column(apps, schema_editor):
    Opportunity = apps.get_model("cpq", "Opportunity")
    Contract = apps.get_model("cpq", "Contract")

    opportunity_table = Opportunity._meta.db_table
    contract_table = Contract._meta.db_table

    existing_tables = set(schema_editor.connection.introspection.table_names())

    # Safety for inconsistent migration history.
    if opportunity_table not in existing_tables:
        schema_editor.create_model(Opportunity)
        existing_tables.add(opportunity_table)

    if contract_table not in existing_tables:
        schema_editor.create_model(Contract)
        return

    opportunity_field = Contract._meta.get_field("opportunity")
    opportunity_column = opportunity_field.column

    if _column_exists(schema_editor.connection, contract_table, opportunity_column):
        return

    # Add as nullable to avoid failures for existing Contract rows (if any).
    field = models.ForeignKey(
        Opportunity,
        on_delete=django.db.models.deletion.CASCADE,
        related_name="contracts",
        null=True,
        blank=True,
    )
    field.set_attributes_from_name("opportunity")
    schema_editor.add_field(Contract, field)


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("cpq", "0018_subscription_contract_field"),
    ]

    operations = [
        migrations.RunPython(ensure_contract_opportunity_column, migrations.RunPython.noop),
    ]

