# Generated by Django 5.2.4 on 2025-08-06 22:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpq', '0018_customfield_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customfieldvalue',
            name='record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_field_values', to='cpq.customrecord'),
        ),
    ]
