# Generated by Django 5.1.5 on 2025-12-27

from django.db import migrations


def create_scheduledtask_table_if_missing(apps, schema_editor):
    ScheduledTask = apps.get_model("cpq", "ScheduledTask")
    table_name = ScheduledTask._meta.db_table

    if table_name in schema_editor.connection.introspection.table_names():
        return

    schema_editor.create_model(ScheduledTask)


class Migration(migrations.Migration):
    # MySQL forbids DDL inside a transaction when it can't be rolled back.
    atomic = False

    dependencies = [
        ("cpq", "0019_contract_opportunity_field"),
    ]

    operations = [
        migrations.RunPython(create_scheduledtask_table_if_missing, migrations.RunPython.noop),
    ]

