# Generated by Django 5.2.4 on 2025-08-08 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpq', '0019_alter_customfieldvalue_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='customrecord',
            name='custom_identifier',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
