# Generated by Django 5.1.5 on 2025-12-27

from django.db import migrations


def drop_contract_subscription_legacy_fk(apps, schema_editor):
    """
    Some environments ended up with a legacy `cpq_contract.subscription_id` FK
    to `cpq_subscription(id)` even though the current Contract model does not
    define that field. If the column is NOT NULL with a default, inserts into
    cpq_contract can fail with FK constraint errors.

    This migration safely removes the FK (if present) and drops the column.
    It's idempotent and safe to re-run.
    """
    Contract = apps.get_model("cpq", "Contract")
    table_name = Contract._meta.db_table
    column_name = "subscription_id"

    with schema_editor.connection.cursor() as cursor:
        # Column exists?
        cursor.execute(
            """
            SELECT COUNT(*)
            FROM information_schema.columns
            WHERE table_schema = DATABASE()
              AND table_name = %s
              AND column_name = %s
            """,
            [table_name, column_name],
        )
        if not cursor.fetchone()[0]:
            return

        # Drop FK constraints referencing this column (if any).
        cursor.execute(
            """
            SELECT DISTINCT constraint_name
            FROM information_schema.key_column_usage
            WHERE table_schema = DATABASE()
              AND table_name = %s
              AND column_name = %s
              AND referenced_table_name IS NOT NULL
            """,
            [table_name, column_name],
        )
        for (constraint_name,) in cursor.fetchall():
            try:
                cursor.execute(
                    f"ALTER TABLE `{table_name}` DROP FOREIGN KEY `{constraint_name}`"
                )
            except Exception:
                # If it's already gone, keep going.
                pass

        # Finally, drop the column itself.
        try:
            cursor.execute(f"ALTER TABLE `{table_name}` DROP COLUMN `{column_name}`")
        except Exception:
            pass


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("cpq", "0020_create_scheduledtask_table_if_missing"),
    ]

    operations = [
        migrations.RunPython(drop_contract_subscription_legacy_fk, migrations.RunPython.noop),
    ]

