# Generated by Django 5.2.4 on 2025-08-08 23:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpq', '0020_customrecord_custom_identifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='customfieldvalue',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
