# Generated by Django 5.1.5 on 2026-01-10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import cpq.models


class Migration(migrations.Migration):

    dependencies = [
        ("cpq", "0021_drop_contract_subscription_legacy_fk"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PartnerProfile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_partner", models.BooleanField(default=True)),
                ("partner_name", models.CharField(blank=True, max_length=255)),
                ("partner_logo", models.ImageField(blank=True, null=True, upload_to=cpq.models.partner_logo_path)),
                ("brand_color", models.CharField(blank=True, max_length=7, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("accounts", models.ManyToManyField(blank=True, related_name="partner_profiles", to="cpq.account")),
                ("contacts", models.ManyToManyField(blank=True, related_name="partner_profiles", to="cpq.contact")),
                ("user", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="partner_profile", to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
