# Generated by Django 5.2.1 on 2025-08-13 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpq', '0021_customfieldvalue_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customrecord',
            name='object_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='cpq.customobject'),
        ),
    ]
