# Generated by Django 5.2.1 on 2025-08-19 17:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpq', '0022_alter_customrecord_object_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('trigger', models.CharField(choices=[('lead_created', 'New Lead Created'), ('account_created', 'New Account Created'), ('opportunity_created', 'New Opportunity Created'), ('opportunity_closed_won', 'Opportunity Closed Won'), ('opportunity_closed_lost', 'Opportunity Closed Lost'), ('quote_sent_for_approval', 'Quote Sent for Approval'), ('quote_approved', 'Quote Approved'), ('quote_rejected', 'Quote Rejected'), ('quote_expiring', 'Quote Expiring Soon'), ('subscription_renewal', 'Subscription Renewal Reminder')], max_length=50)),
                ('native_object', models.CharField(blank=True, choices=[('Lead', 'Lead'), ('Account', 'Account'), ('Opportunity', 'Opportunity'), ('Quote', 'Quote'), ('Subscription', 'Subscription')], help_text='Select a native object', max_length=50, null=True)),
                ('recipients_roles', models.CharField(blank=True, choices=[('all_superadmins', 'All Superadmins'), ('all_admins', 'All Admins'), ('all_staff', 'All Staff'), ('creator', 'Creator')], help_text='Select the role of the recipients', max_length=50, null=True)),
                ('recipients_external', models.TextField(blank=True, help_text='External emails separated by commas', null=True)),
                ('offset_days', models.IntegerField(blank=True, help_text='E.g., send 7 days before the expiration date (for subscriptions, quotes, etc.)', null=True)),
                ('scheduled_cron', models.CharField(blank=True, help_text="Cron format or text like 'every other Friday at noon'", max_length=100, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_alerts_created', to=settings.AUTH_USER_MODEL)),
                ('custom_object', models.ForeignKey(blank=True, help_text='Select a custom object', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cpq.customobject')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_alerts_updated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmailAlertRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emailalert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cpq.emailalert')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('emailalert', 'user')},
            },
        ),
        migrations.DeleteModel(
            name='EmailNotification',
        ),
        migrations.AddField(
            model_name='emailalert',
            name='recipients_users',
            field=models.ManyToManyField(blank=True, related_name='email_alerts', through='cpq.EmailAlertRecipient', to=settings.AUTH_USER_MODEL),
        ),
    ]
