# Generated by Django 5.2.1 on 2025-08-19 17:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpq', '0023_emailalert_emailalertrecipient_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailalertrecipient',
            old_name='emailalert',
            new_name='email_alert',
        ),
        migrations.AlterField(
            model_name='emailalert',
            name='recipients_roles',
            field=models.CharField(blank=True, choices=[('all_superusers', 'All Superusers'), ('all_admins', 'All Admins'), ('all_staff', 'All Staff'), ('creator', 'Creator')], help_text='Select the role of the recipients', max_length=50, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='emailalertrecipient',
            unique_together={('email_alert', 'user')},
        ),
    ]
