# Generated by Django 5.2.4 on 2025-08-22 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpq', '0024_rename_emailalert_emailalertrecipient_email_alert_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailalert',
            name='recipients_roles',
            field=models.CharField(blank=True, help_text='Select the role of the recipients', max_length=50, null=True),
        ),
    ]
