# Generated by Django 5.2.1 on 2025-08-29 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpq', '0026_quote_updated_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailAlertLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance_type', models.CharField(max_length=50)),
                ('instance_id', models.BigIntegerField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('email_alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cpq.emailalert')),
            ],
            options={
                'ordering': ['-sent_at'],
                'unique_together': {('email_alert', 'instance_type', 'instance_id')},
            },
        ),
    ]
