# Generated by Django 5.1.5 on 2026-01-18 22:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


def create_cpqsettings_if_missing(apps, schema_editor):
    table_name = "cpq_cpqsettings"
    existing = schema_editor.connection.introspection.table_names()
    if table_name in existing:
        return

    CPQSettings = apps.get_model("cpq", "CPQSettings")
    schema_editor.create_model(CPQSettings)


def backfill_public_ids(apps, schema_editor):
    models_to_update = [
        apps.get_model("cpq", "Product"),
        apps.get_model("cpq", "Quote"),
        apps.get_model("cpq", "QuoteLine"),
        apps.get_model("cpq", "Subscription"),
    ]

    for model in models_to_update:
        for row in model.objects.filter(public_id__isnull=True).iterator():
            row.public_id = uuid.uuid4()
            row.save(update_fields=["public_id"])


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("cpq", "0028_tenant_sidebar_standard_objects"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.CreateModel(
                    name="CPQSettings",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        (
                            "renewal_forecast_window_days",
                            models.PositiveIntegerField(default=90),
                        ),
                        (
                            "quote_expiration_default_days",
                            models.PositiveIntegerField(default=30),
                        ),
                        ("decimal_precision", models.PositiveSmallIntegerField(default=2)),
                        ("rounding_mode", models.CharField(default="HALF_EVEN", max_length=20)),
                        ("proration_enabled", models.BooleanField(default=True)),
                        (
                            "proration_method",
                            models.CharField(default="MONTHLY_SIMPLE", max_length=30),
                        ),
                        (
                            "day_count_convention",
                            models.CharField(default="ACTUAL", max_length=20),
                        ),
                        ("forecast_opportunity_enabled", models.BooleanField(default=True)),
                        (
                            "forecast_opportunity_creation_mode",
                            models.CharField(default="RENEWAL_ONLY", max_length=30),
                        ),
                        (
                            "forecast_opportunity_stage",
                            models.CharField(default="Forecast", max_length=50),
                        ),
                        (
                            "forecast_opportunity_probability",
                            models.PositiveSmallIntegerField(default=70),
                        ),
                        (
                            "forecast_amount_strategy",
                            models.CharField(default="TOTAL_CONTRACT_VALUE", max_length=40),
                        ),
                        (
                            "auto_recalculate_renewals_on_amendment",
                            models.BooleanField(default=True),
                        ),
                        ("ramp_deals_enabled", models.BooleanField(default=True)),
                        ("created_at", models.DateTimeField(auto_now_add=True)),
                        ("updated_at", models.DateTimeField(auto_now=True)),
                    ],
                    options={
                        "verbose_name": "CPQ Settings",
                        "verbose_name_plural": "CPQ Settings",
                    },
                ),
            ],
        ),
        migrations.RunPython(create_cpqsettings_if_missing, migrations.RunPython.noop),
        migrations.AddField(
            model_name="product",
            name="public_id",
            field=models.UUIDField(editable=False, unique=True, null=True, blank=True),
        ),
        migrations.AddField(
            model_name="quote",
            name="public_id",
            field=models.UUIDField(editable=False, unique=True, null=True, blank=True),
        ),
        migrations.AddField(
            model_name="quoteline",
            name="public_id",
            field=models.UUIDField(editable=False, unique=True, null=True, blank=True),
        ),
        migrations.AddField(
            model_name="subscription",
            name="public_id",
            field=models.UUIDField(editable=False, unique=True, null=True, blank=True),
        ),
        migrations.RunPython(backfill_public_ids, migrations.RunPython.noop),
        migrations.CreateModel(
            name="Amendment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amendment_type", models.CharField(blank=True, max_length=30)),
                ("effective_date", models.DateField(blank=True, null=True)),
                ("status", models.CharField(blank=True, max_length=30)),
                (
                    "public_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "quote",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="amendments",
                        to="cpq.quote",
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="amendments",
                        to="cpq.subscription",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PricingTierTable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("currency", models.CharField(blank=True, max_length=10, null=True)),
                ("uom", models.CharField(blank=True, max_length=20, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("effective_start_date", models.DateField(blank=True, null=True)),
                ("effective_end_date", models.DateField(blank=True, null=True)),
                (
                    "public_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pricing_tier_tables",
                        to="cpq.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pricing Tier Table",
                "verbose_name_plural": "Pricing Tier Tables",
            },
        ),
        migrations.CreateModel(
            name="PricingTierRow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("min_quantity", models.PositiveIntegerField()),
                ("max_quantity", models.PositiveIntegerField(blank=True, null=True)),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "public_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "pricing_table",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tier_rows",
                        to="cpq.pricingtiertable",
                    ),
                ),
            ],
            options={
                "ordering": ["min_quantity"],
            },
        ),
        migrations.CreateModel(
            name="QuoteLineSegment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "discount_percentage",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                (
                    "discount_amount",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "subtotal",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "total_price",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                (
                    "public_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "quote_line",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="segments",
                        to="cpq.quoteline",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "start_date"],
            },
        ),
        migrations.CreateModel(
            name="Renewal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("renewal_date", models.DateField(blank=True, null=True)),
                ("status", models.CharField(blank=True, max_length=30)),
                (
                    "forecast_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "quote",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="renewals",
                        to="cpq.quote",
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="renewals",
                        to="cpq.subscription",
                    ),
                ),
            ],
        ),
    ]
