# Generated by Django 5.1.5 on 2026-01-18 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cpq", "0031_alter_pricingtierrow_public_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pricebookentry",
            name="currency_iso_code",
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
