# Generated by Django 5.1.5 on 2026-01-19 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cpq", "0032_pricebookentry_currency_iso_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="amendment",
            name="proration_multiplier",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=10, null=True
            ),
        ),
        migrations.CreateModel(
            name="AmendmentDelta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("field_name", models.CharField(max_length=255)),
                ("old_value", models.JSONField(blank=True, null=True)),
                ("new_value", models.JSONField(blank=True, null=True)),
                (
                    "delta_value",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=18, null=True
                    ),
                ),
                (
                    "prorated_value",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=18, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "amendment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deltas",
                        to="cpq.amendment",
                    ),
                ),
            ],
            options={
                "unique_together": {("amendment", "field_name")},
            },
        ),
    ]
