# Generated by Django 5.1.5 on 2026-01-19 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cpq", "0033_amendment_proration_multiplier_amendmentdelta"),
    ]

    operations = [
        migrations.CreateModel(
            name="DomainEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_type", models.CharField(db_index=True, max_length=100)),
                (
                    "object_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("object_id", models.CharField(blank=True, max_length=100, null=True)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("idempotency_key", models.CharField(max_length=200, unique=True)),
                ("source", models.CharField(blank=True, default="", max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AlterField(
            model_name="quote",
            name="status",
            field=models.CharField(
                choices=[
                    ("Draft", "Draft"),
                    ("Forecast", "Forecast"),
                    ("Pending Approval", "Pending Approval"),
                    ("Approved", "Approved"),
                    ("Rejected", "Rejected"),
                    ("Closed", "Closed"),
                ],
                default="Draft",
                max_length=50,
            ),
        ),
    ]
