# Generated by Django 5.1.5 on 2026-09-03 15:35

import cpq.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("contenttypes", "0002_remove_content_type_name"),
        ("cpq", "0041_alter_opportunity_expected_close_date"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ScheduledEmail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "instance_model",
                    models.CharField(
                        help_text="e.g. 'cpq.Opportunity'", max_length=100
                    ),
                ),
                ("instance_id", models.BigIntegerField()),
                (
                    "action",
                    models.JSONField(
                        default=dict,
                        help_text="The EMAIL action dict to execute at send time.",
                    ),
                ),
                ("send_at", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("attempts", models.IntegerField(default=0)),
                ("last_error", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Scheduled Email",
                "verbose_name_plural": "Scheduled Emails",
            },
        ),
        migrations.RemoveConstraint(
            model_name="recordaccessgrant",
            name="record_access_grant_user_xor_group",
        ),
        migrations.RenameIndex(
            model_name="recordaccessgrant",
            new_name="cpq_recorda_content_14c040_idx",
            old_name="cpq_recorda_content_518edd_idx",
        ),
        migrations.RenameIndex(
            model_name="recordaccessgrant",
            new_name="cpq_recorda_user_id_d35c7c_idx",
            old_name="cpq_recorda_user_id_11cd8f_idx",
        ),
        migrations.RenameIndex(
            model_name="recordaccessgrant",
            new_name="cpq_recorda_group_i_32fad9_idx",
            old_name="cpq_recorda_group_i_65db8b_idx",
        ),
        migrations.AddField(
            model_name="actiontrigger",
            name="schedule_config",
            field=models.JSONField(
                blank=True,
                help_text='For \'offset\': {"date_field": "expiration_date", "offset_days": -7} (negative = before). For \'date\': {"send_at": "2026-09-15T09:00:00"}.',
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="actiontrigger",
            name="schedule_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("immediate", "Immediate"),
                    ("offset", "Relative to a record date"),
                    ("date", "Specific date/time"),
                ],
                default="immediate",
                help_text="When to deliver the email. 'immediate' sends on the event; 'offset' sends N days before/after a record date; 'date' sends at a fixed date/time.",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="opportunity",
            name="expected_close_date",
            field=models.DateField(
                blank=True,
                default=cpq.models.default_opportunity_expected_close_date,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="quoteline",
            name="public_id",
            field=models.UUIDField(
                blank=True, default=uuid.uuid4, editable=False, null=True, unique=True
            ),
        ),
        migrations.AddConstraint(
            model_name="recordaccessgrant",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("user__isnull", False), ("group__isnull", True)),
                    models.Q(("user__isnull", True), ("group__isnull", False)),
                    _connector="OR",
                ),
                name="record_access_grant_user_xor_group",
            ),
        ),
        migrations.AddField(
            model_name="scheduledemail",
            name="trigger",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scheduled_emails",
                to="cpq.actiontrigger",
            ),
        ),
        migrations.AddIndex(
            model_name="scheduledemail",
            index=models.Index(
                fields=["status", "send_at"], name="cpq_schedul_status_e940e0_idx"
            ),
        ),
    ]
