# Generated by Django 5.1.5 on 2026-09-04 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cpq", "0042_scheduledemail_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="company",
            field=models.CharField(
                blank=True, help_text="Company the lead works for.", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="converted_at",
            field=models.DateTimeField(
                blank=True, help_text="When this lead was converted.", null=True
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="rating",
            field=models.CharField(
                blank=True,
                choices=[("hot", "Hot"), ("warm", "Warm"), ("cold", "Cold")],
                default="warm",
                help_text="Lead quality/priority.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="title",
            field=models.CharField(blank=True, help_text="Job title.", max_length=100),
        ),
        migrations.AddField(
            model_name="lead",
            name="website",
            field=models.URLField(blank=True, help_text="Company website.", null=True),
        ),
    ]
