# Generated by Django 5.1.5 on 2026-09-04 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cpq", "0043_lead_company_lead_converted_at_lead_rating_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="converted_account",
            field=models.ForeignKey(
                blank=True,
                help_text="The Account created when this lead was converted.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="converted_leads",
                to="cpq.account",
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="converted_opportunity",
            field=models.ForeignKey(
                blank=True,
                help_text="The Opportunity created when this lead was converted.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="converted_leads",
                to="cpq.opportunity",
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="do_not_call",
            field=models.BooleanField(
                default=False, help_text="Compliance: suppress phone outreach."
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="email_opt_out",
            field=models.BooleanField(
                default=False, help_text="Compliance: suppress email outreach."
            ),
        ),
    ]
