# Generated by Django 5.1.5 on 2026-09-04 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cpq", "0044_lead_converted_account_lead_converted_opportunity_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="do_not_call",
            field=models.BooleanField(
                default=False, help_text="Compliance: suppress phone outreach."
            ),
        ),
        migrations.AddField(
            model_name="contact",
            name="email_opt_out",
            field=models.BooleanField(
                default=False, help_text="Compliance: suppress email outreach."
            ),
        ),
    ]
