# Generated by Django 5.1.5 on 2026-09-04 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cpq", "0045_contact_do_not_call_contact_email_opt_out"),
    ]

    operations = [
        migrations.AddField(
            model_name="opportunity",
            name="nacv",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="New Annual Contract Value of the renewal (from the renewal quote).",
                max_digits=14,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="opportunity",
            name="renewal_baseline",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Value of the expiring contract/deal this renewal replaces.",
                max_digits=14,
                null=True,
            ),
        ),
    ]
