# Generated by Django 5.1.5 on 2026-09-04 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cpq", "0046_opportunity_nacv_opportunity_renewal_baseline"),
    ]

    operations = [
        migrations.AddField(
            model_name="opportunity",
            name="renews_opportunity",
            field=models.ForeignKey(
                blank=True,
                help_text="The original opportunity this renewal opportunity replaces.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="renewals",
                to="cpq.opportunity",
            ),
        ),
    ]
