# Generated by Django 5.1.5 on 2026-09-11 22:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cpq", "0047_opportunity_renews_opportunity"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ObjectRelationConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "parent_object",
                    models.CharField(
                        help_text="Object whose form shows the section (e.g. Opportunity, Account, or a custom object like pov__c).",
                        max_length=100,
                    ),
                ),
                (
                    "related_object",
                    models.CharField(
                        help_text="Related object to list in that form (e.g. pov__c, Quote, Activity, Contract).",
                        max_length=100,
                    ),
                ),
                (
                    "link_field",
                    models.CharField(
                        blank=True,
                        help_text="Field on the related object that points to the parent record (e.g. opportunity__c for a custom object, 'opportunity' for quotes). Leave blank to auto-detect.",
                        max_length=100,
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True,
                        help_text="Section title shown in the form (defaults to the related object's label).",
                        max_length=100,
                    ),
                ),
                (
                    "position",
                    models.PositiveIntegerField(
                        default=100,
                        help_text="Order of the section in the form (lower = earlier).",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_object_relations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Object Related Section",
                "verbose_name_plural": "Object Related Sections",
                "ordering": ["parent_object", "position", "id"],
                "unique_together": {("parent_object", "related_object", "link_field")},
            },
        ),
    ]
