# Generated by Django 5.1.5 on 2026-09-13 23:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cpq", "0048_objectrelationconfig"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="activities",
                to="cpq.account",
            ),
        ),
    ]
