# Generated by Django 5.1.5 on 2026-09-17 16:35

from django.db import migrations, models


STAGE_PROBABILITIES = {
    "appointmentscheduled": 10,
    "qualifiedtobuy": 20,
    "presentationscheduled": 40,
    "decisionmakerboughtin": 60,
    "contractsent": 80,
    "disqualified": 0,
    "closedwon": 100,
    "closedlost": 0,
}


def seed_stage_probabilities(apps, schema_editor):
    OpportunityStage = apps.get_model("cpq", "OpportunityStage")
    for key, probability in STAGE_PROBABILITIES.items():
        OpportunityStage.objects.filter(key=key).update(probability=probability)


def reset_stage_probabilities(apps, schema_editor):
    OpportunityStage = apps.get_model("cpq", "OpportunityStage")
    OpportunityStage.objects.filter(key__in=list(STAGE_PROBABILITIES)).update(probability=50)


class Migration(migrations.Migration):

    dependencies = [
        ("cpq", "0050_add_disqualified_opportunity_stage"),
    ]

    operations = [
        migrations.CreateModel(
            name="BusinessDashboard",
            fields=[],
            options={
                "verbose_name": "Business Dashboard",
                "verbose_name_plural": "Business Dashboard",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("cpq.opportunity",),
        ),
        migrations.AddField(
            model_name="opportunitystage",
            name="probability",
            field=models.PositiveSmallIntegerField(
                default=50,
                help_text="Win probability (0-100) used for the weighted forecast.",
            ),
        ),
        migrations.RunPython(seed_stage_probabilities, reset_stage_probabilities),
    ]
