# Generated by Django 5.1.5 on 2026-09-23 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cpq", "0051_businessdashboard_customobjectrecord1_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomObjectRecord1",
            fields=[],
            options={
                "verbose_name": "POV",
                "verbose_name_plural": "POV",
                "managed": True,
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("cpq.customrecord",),
        ),
        migrations.AlterField(
            model_name="quoteapproval",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Approved", "Approved"),
                    ("Rejected", "Rejected"),
                    ("Recalled", "Recalled"),
                ],
                default="Pending",
                max_length=50,
            ),
        ),
    ]
