"""
Django settings for agentcpq project.

Generated by 'django-admin startproject' using Django 4.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
import logging
from dotenv import load_dotenv
import dj_database_url
from decouple import config

NGROK_FULL_URL = "https://0d0e3e34c51c.ngrok-free.app"
NGROK_URI = "0d0e3e34c51c.ngrok-free.app"

load_dotenv()
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-bub3zw@!0=_wdp43tnesi*7!j5&yw3n4ejp(q5fni87n_2lc5%"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# ALLOWED_HOSTS = []
ALLOWED_HOSTS = [
    '127.0.0.1',
    'localhost',
    NGROK_URI,
    '.herokuapp.com',
    'sympletech.agentcpq.ai',
]

# Allow Django to be embedded in an IFrame (required for Salesforce)
X_FRAME_OPTIONS = 'ALLOWALL'

CSRF_COOKIE_SECURE = True
SESSION_COOKIE_SECURE = True
SESSION_COOKIE_AGE = 86400
SESSION_EXPIRE_AT_BROWSER_CLOSE = False

CORS_ALLOWED_ORIGINS = [
    NGROK_FULL_URL
]

# ✅ Allow all domains in development (Use only for testing)
CSRF_COOKIE_DOMAIN = None
CSRF_COOKIE_SECURE = True
SESSION_COOKIE_SECURE = True

CSRF_TRUSTED_ORIGINS = [
    NGROK_FULL_URL
]

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "cpq",
    "agents",
    "dashboard",
    "salesforce",
    "hubspot",
    'django.contrib.humanize',
    'storages',
    'api'
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "cpq.middleware.SaveLastDashboardSessionMiddleware",
]

ROOT_URLCONF = "agentcpq.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        'DIRS': [BASE_DIR / 'cpq' / 'templates'],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "agentcpq.wsgi.application"


# Database
DATABASES = {
    'default': dj_database_url.config(
        default=config('DATABASE_URL'),
        conn_max_age=config('CONN_MAX_AGE', cast=int, default=600),
    )
}

default_db = DATABASES.get('default', {})
engine = default_db.get('ENGINE', '')
if engine.endswith('mysql'):
    mysql_options = default_db.setdefault('OPTIONS', {})
    mysql_options.setdefault('charset', 'utf8mb4')
    mysql_options.setdefault('use_unicode', True)

    init_command = "SET NAMES 'utf8mb4' COLLATE 'utf8mb4_unicode_ci'"
    existing_init = mysql_options.get('init_command')
    if existing_init and existing_init.strip() != init_command:
        mysql_options['init_command'] = existing_init
    else:
        mysql_options['init_command'] = init_command

    default_db.setdefault('TEST', {})
    default_db['TEST'].setdefault('CHARSET', 'utf8mb4')
    default_db['TEST'].setdefault('COLLATION', 'utf8mb4_unicode_ci')

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/dashboard/'
LOGOUT_REDIRECT_URL = '/login/'

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

USE_TZ = True
TIME_ZONE = "UTC"

USE_I18N = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATIC_URL = '/static/'
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"


STATICFILES_DIRS = [
     BASE_DIR / 'static'
]


# STATIC_URL = '/static/'

# STATICFILES_DIRS = [
#      BASE_DIR / 'static'
# ]

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
CSP_DEFAULT_SRC = ("'self'",)
CSP_SCRIPT_SRC = ("'self'", "https://cdnjs.cloudflare.com")  # Allow scripts only from trusted sources
CSP_STYLE_SRC = ("'self'", "https://fonts.googleapis.com")  # Allow Google Fonts
CSP_FONT_SRC = ("'self'", "https://fonts.gstatic.com")  # Allow Google Fonts
CSP_IMG_SRC = ("'self'", "data:")  # Allow local images and data URIs
CSP_CONNECT_SRC = ("'self'",)  # Restrict API calls to your own server


# ✅ Set default logging level (change to INFO if you want fewer logs)
logging.basicConfig(
    level=logging.DEBUG,  # Change to DEBUG if needed
    format="%(levelname)s:%(name)s:%(message)s"
)

# ✅ Suppress noisy libraries (OpenAI, HTTPX, and HTTPCore)
# logging.getLogger("openai").setLevel(logging.WARNING)  # Hide OpenAI debug logs
logging.getLogger("httpx").setLevel(logging.WARNING)  # Suppress HTTP client logs
logging.getLogger("httpcore").setLevel(logging.WARNING)  # Suppress low-level HTTP logs

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Cloudflare R2 ENV Vars
R2_ACCESS_KEY_ID = os.getenv("R2_ACCESS_KEY")
R2_SECRET_ACCESS_KEY = os.getenv("R2_SECRET")
R2_STORAGE_BUCKET_NAME = os.getenv("R2_BUCKET_NAME")
R2_S3_ENDPOINT_URL = os.getenv("R2_END_POINT")

# AWS Settings Required by django-storages
AWS_ACCESS_KEY_ID = R2_ACCESS_KEY_ID
AWS_SECRET_ACCESS_KEY = R2_SECRET_ACCESS_KEY
AWS_STORAGE_BUCKET_NAME = R2_STORAGE_BUCKET_NAME
AWS_S3_ENDPOINT_URL = R2_S3_ENDPOINT_URL
AWS_S3_REGION_NAME = "auto"
AWS_S3_ADDRESSING_STYLE = "virtual"
AWS_QUERYSTRING_AUTH = False
AWS_S3_CUSTOM_DOMAIN = "media.agentcpq.com"

# ⚠️ Must come after AWS_* settings
DEFAULT_FILE_STORAGE = "storages.backends.s3boto3.S3Boto3Storage"


# Salesforce OAuth settings for your connected app
SALESFORCE_CLIENT_ID = os.getenv("SF_CID")
SALESFORCE_CLIENT_SECRET = os.getenv("SF_SECRET")
SALESFORCE_REDIRECT_URI = "https://b377-2607-fb91-a06-c34d-44ac-db3b-c577-9f3a.ngrok-free.app/salesforce/callback"
SALESFORCE_AUTH_URL = "https://login.salesforce.com/services/oauth2/authorize"
SALESFORCE_TOKEN_URL = "https://login.salesforce.com/services/oauth2/token"

# For reset password

def _clean_mail_credential(value):
    if value is None:
        return None
    value = value.replace('\xa0', ' ').strip()
    return value or None

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = _clean_mail_credential(os.getenv("GMAIL_USER"))
EMAIL_HOST_PASSWORD = _clean_mail_credential(os.getenv("GMAIL_APP_PW"))
_default_reply_address = _clean_mail_credential(os.getenv("DEFAULT_FROM_EMAIL")) or "noreply@sympletechsolutions.com"
DEFAULT_FROM_EMAIL = f"Symple Tech Solutions <{_default_reply_address}>"
DEFAULT_REPLY_TO = _default_reply_address
