# Generated by Django 5.1.5 on 2025-10-13 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="QuickbooksToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_id",
                    models.CharField(
                        default="default",
                        help_text="Identifier used to scope the stored credentials.",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "realm_id",
                    models.CharField(
                        help_text="QuickBooks company (realm) identifier.",
                        max_length=100,
                    ),
                ),
                ("access_token", models.TextField()),
                ("refresh_token", models.TextField(blank=True, null=True)),
                ("token_type", models.CharField(default="bearer", max_length=30)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "refresh_token_expires_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "QuickBooks Token",
                "verbose_name_plural": "QuickBooks Tokens",
            },
        ),
    ]
