import json, os, re
import openai
import logging
from dotenv import load_dotenv
from cpq.models import CustomObject
from django.apps import apps

load_dotenv()
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")
OPENAI_MODEL = "gpt-4o-mini"

client = openai.OpenAI(api_key=OPENAI_API_KEY)


# ---------------------------------------------------------
# ✅ Helpers
# ---------------------------------------------------------

def to_snake_case(name):
    return re.sub(r'(?<!^)(?=[A-Z])', '_', name).lower()


def get_field_type(field):
    t = field.get_internal_type().lower()
    if "char" in t or "text" in t:
        return "string"
    if "bool" in t:
        return "boolean"
    if "int" in t or "float" in t or "decimal" in t:
        return "number"
    if "json" in t:
        return "json"
    return t


def build_model_schema():
    """
    ✅ Generates a schema of all models + custom objects + fields + relations.
    Fully safe for reverse relations.
    schema = {
      "<model>": {
         "fields": { "<field>": "type", ... },
         "relations": { "<rel_name>": "<related_model>", ... }
      },
      ...
    }
    """
    schema = {}

    # Core models
    for model in apps.get_app_config("cpq").get_models():
        mname = to_snake_case(model.__name__)
        schema[mname] = {"fields": {}, "relations": {}}

        for field in model._meta.get_fields():
            # Ignore autogenerated reverse relations
            if field.auto_created and not field.concrete:
                continue

            # Relation
            if field.is_relation:
                rmodel = getattr(field, "related_model", None)
                if rmodel is None:
                    continue
                if not hasattr(rmodel, "__name__"):
                    continue
                schema[mname]["relations"][field.name] = to_snake_case(rmodel.__name__)
                continue

            # Normal field
            try:
                schema[mname]["fields"][field.name] = get_field_type(field)
            except Exception:
                schema[mname]["fields"][field.name] = "unknown"

    # ✅ Custom Objects (fields end with __c)
    for obj in CustomObject.objects.all():
        oname = to_snake_case(obj.name)
        schema[oname] = {"fields": {}, "relations": {}}

        # Preferred related_name: custom_fields; fallback: customfield_set
        if hasattr(obj, "custom_fields"):
            cfields = obj.custom_fields.all()
        elif hasattr(obj, "customfield_set"):
            cfields = obj.customfield_set.all()
        else:
            cfields = []

        for cf in cfields:
            fname = f"{cf.name}__c" if not cf.name.endswith("__c") else cf.name
            dt = (cf.data_type or "").lower()
            if dt in ["text", "string"]:
                schema[oname]["fields"][fname] = "string"
            elif dt in ["number", "currency", "integer", "float", "decimal"]:
                schema[oname]["fields"][fname] = "number"
            elif dt == "boolean":
                schema[oname]["fields"][fname] = "boolean"
            else:
                schema[oname]["fields"][fname] = "string"

    # ---------------------------------------------------------
    # 3️⃣ Custom Fields linked to Standard Objects (custom_object_id = NULL)
    # ---------------------------------------------------------
    from cpq.models import CustomField

    for cf in CustomField.objects.filter(custom_object__isnull=True):
        obj_type = cf.object_type.lower()
        if obj_type not in schema:
            continue  # Skip unknown or missing base model

        fname = cf.name if cf.name.endswith("__c") else f"{cf.name}__c"
        dt = (cf.data_type or "").lower()

        if dt in ["text", "string"]:
            schema[obj_type]["fields"][fname] = "string"
        elif dt in ["number", "currency", "integer", "float", "decimal"]:
            schema[obj_type]["fields"][fname] = "number"
        elif dt == "boolean":
            schema[obj_type]["fields"][fname] = "boolean"
        else:
            schema[obj_type]["fields"][fname] = "string"

    return schema


# ---------------------------------------------------------
# ✅ Path resolution (no cambia formato; solo corrige rutas)
# ---------------------------------------------------------

def _fix_double_c(path: str):
    if not isinstance(path, str):
        return path
    # Collapse any repeated "__c" at the end (e.g., "__c__c" → "__c")
    return re.sub(r'(__c)+$', '__c', path)


def _variants_for_field_name(raw: str):
    """Return possible variants to match a field in schema."""
    base = raw.rstrip('_')
    variants = [raw]
    if not raw.endswith("__c"):
        variants.append(f"{raw}__c")
    if raw.endswith("__c"):
        variants.append(raw[:-3])  # try without __c
    # also normalized snake
    s = to_snake_case(base)
    if s not in variants:
        variants.append(s)
    if not s.endswith("__c"):
        variants.append(f"{s}__c")
    return list(dict.fromkeys(variants))  # unique, keep order


def _find_field_path(schema, start_model, target_field, max_depth=4):
    """
    DFS over relations to find a path from start_model to any model containing target_field.
    Returns dot path like "rel1.rel2.field".
    """
    if start_model not in schema:
        return None
    target_variants = _variants_for_field_name(target_field)

    # If field already in root:
    for tv in target_variants:
        if tv in schema[start_model]["fields"]:
            return tv  # just the field

    # DFS
    stack = [(start_model, [], 0)]
    visited = set()
    while stack:
        model, rel_path, depth = stack.pop()
        if depth > max_depth:
            continue
        key = (model, tuple(rel_path))
        if key in visited:
            continue
        visited.add(key)

        # Check fields at this model
        for tv in target_variants:
            if tv in schema[model]["fields"]:
                return ".".join(rel_path + [tv])

        # Traverse relations
        for rel_name, next_model in (schema[model]["relations"] or {}).items():
            if next_model in schema:
                stack.append((next_model, rel_path + [rel_name], depth + 1))

    return None


def resolve_path_from_root(schema, root_model, raw_path):
    """
    - If raw_path already has dots, just sanitize __c and return.
    - If raw_path is a single token and not in root, try to discover nested path.
    """
    if not isinstance(raw_path, str) or not raw_path.strip():
        return raw_path

    raw_path = raw_path.strip()
    # If user already provided a dotted path, just sanitize ending
    if "." in raw_path:
        return ".".join(_fix_double_c(p) for p in raw_path.split("."))

    # Single token: check in root model first
    if root_model in schema and raw_path in schema[root_model]["fields"]:
        return raw_path

    # Try to find via relations
    discovered = _find_field_path(schema, root_model, raw_path, max_depth=5)
    if discovered:
        return _fix_double_c(discovered)

    # Try with "__c" explicitly
    if not raw_path.endswith("__c"):
        discovered = _find_field_path(schema, root_model, f"{raw_path}__c", max_depth=5)
        if discovered:
            return _fix_double_c(discovered)

    # Fallback: return sanitized input
    return _fix_double_c(raw_path)


def normalize_event_type(evt, available_models):
    """
    Coerce action to allowed set and validate object_type.
    """
    if not isinstance(evt, dict):
        return None
    obj = evt.get("object_type")
    act = (evt.get("action") or "").lower().strip()
    action_map = {"created": "create", "updated": "update", "deleted": "delete"}
    act = action_map.get(act, act)
    if obj not in available_models:
        return None
    if act not in ["create", "update", "delete"]:
        return None
    return {"object_type": obj, "action": act}


def actions_are_valid(actions):
    """
    VALIDATION RULES (UPDATED WITH BULK FILTERS SUPPORT)

    Supports:
    - CREATE with fields (normal)
    - CREATE with filters (bulk create)
    - UPDATE with path (normal)
    - UPDATE with filters (bulk update)
    - DELETE (unchanged)

    Rules:
    - UPDATE cannot have path AND filters at the same time.
    - CREATE cannot have both fields AND filters at the same time.
    - CREATE must have: either fields OR filters (at least one).
    """

    if not isinstance(actions, list) or not actions:
        return False

    for a in actions:
        if not isinstance(a, dict):
            return False

        op = (a.get("operation") or "").upper()
        target = a.get("target", {})
        value = a.get("value")

        # Must exist
        if not a.get("target"):
            return False

        # ------------------------------
        # CREATE
        # ------------------------------
        if op == "CREATE":
            fields = (value or {}).get("fields")
            filters = target.get("filters")

            # ❌ Cannot have fields + filters simultaneously
            if fields and filters:
                return False

            # ❌ Must have at least one of them
            if not fields and not filters:
                return False

            # If fields exist → must be a dict
            if fields and not isinstance(fields, dict):
                return False

            # target.path must always be None / absent
            if "path" in target and target.get("path") not in (None, ""):
                return False

            # If filters exist → must be list[dict]
            if filters:
                if not isinstance(filters, list):
                    return False
                if not all(isinstance(f, dict) for f in filters):
                    return False

            continue

        # ------------------------------
        # UPDATE
        # ------------------------------
        if op == "UPDATE":
            path = target.get("path")
            filters = target.get("filters")

            # UPDATE must have a value block
            if not value:
                return False

            # ❌ Cannot use path + filters together
            if path and filters:
                return False

            # If path exists → must be string
            if path and not isinstance(path, str):
                return False

            # If filters exist → must be list[dict]
            if filters:
                if not isinstance(filters, list):
                    return False
                if not all(isinstance(f, dict) for f in filters):
                    return False

            # No more constraints
            continue

        # ------------------------------
        # DELETE (unchanged)
        # ------------------------------
        if op == "DELETE":
            filters = target.get("filters")

            if not target.get("object"):
                return False

            if filters:
                if not isinstance(filters, list):
                    return False
                if not all(isinstance(f, dict) for f in filters):
                    return False

            continue

        # Unknown op
        return False

    return True



# ---------------------------------------------------------
# 🔧 Normalizers (mantienen TU formato)
# ---------------------------------------------------------

def _normalize_value_block(v):
    if not isinstance(v, dict):
        return None

    t = v.get("type")

    # Detect expression automatically if missing type but formula exists
    if not t and "formula" in v:
        t = "expression"

    out = {"type": t}

    if t == "field":
        out["object"] = v.get("object")
        out["path"] = v.get("path")
    elif t == "static":
        out["data"] = v.get("data")
    elif t == "expression":
        out["formula"] = v.get("formula")
    elif t == "date":
        out["formula"] = v.get("formula")

    return out


def normalize_conditions(cond):
    if not cond:
        return None
    items = []
    for c in cond.get("items", []):
        items.append({
            "alias": c.get("alias"),
            "left": {
                "object": c.get("left", {}).get("object"),
                "path": c.get("left", {}).get("path")
            },
            "operator": c.get("operator"),
            "right": _normalize_value_block(c.get("right"))
        })
    return {"logic": cond.get("logic", "AND"), "items": items}


def normalize_create_value_fields(fields, schema):
    """
    ✅ For CREATE.value.fields: sanitize each entry WITHOUT changing format.
    - If type == field: ensure object/path exist; sanitize path (__c) using resolve_path_from_root(object).
    - If type == static/expression: keep respective property.
    """
    if not isinstance(fields, dict):
        return {}
    out = {}
    for fname, spec in fields.items():
        if not isinstance(spec, dict):
            continue
        t = spec.get("type")
        # Keep original key
        if t == "field":
            obj = spec.get("object")
            path = spec.get("path")
            if isinstance(obj, str) and isinstance(path, str):
                # Resolve path against the declared object (not the event root)
                norm_path = resolve_path_from_root(schema, obj, path)
            else:
                obj = spec.get("object")
                norm_path = _fix_double_c(spec.get("path"))
            out[fname] = {
                "type": "field",
                "object": obj,
                "path": norm_path
            }
        elif t == "static":
            out[fname] = {"type": "static", "data": spec.get("data")}
        elif t == "expression":
            out[fname] = {"type": "expression", "formula": spec.get("formula")}
        elif t == "date":
            out[fname] = {"type": "date", "formula": spec.get("formula")}
        else:
            # Unknown: drop to avoid {"type": null}
            continue
    return out

def _normalize_filter_list(filters, target_obj, schema):
    """
    Normaliza filters para CREATE, UPDATE y DELETE.
    - Resuelve rutas con resolve_path_from_root
    - Limpia __c__c
    - Valida tipos permitidos
    - Limpia filtros inválidos
    """

    clean = []

    if not filters:
        return clean

    for f in filters:
        if not isinstance(f, dict):
            continue

        raw_field = f.get("field")
        operator  = f.get("operator")
        raw_value = f.get("value")

        if not raw_field or not operator or not raw_value:
            continue

        # 1️⃣ Normalizar path del campo
        field_path = resolve_path_from_root(schema, target_obj, raw_field)
        field_path = _fix_double_c(field_path)

        # 2️⃣ Normalizar el value
        val = _normalize_value_block(raw_value)
        if not isinstance(val, dict):
            continue

        # ❌ NO SE PERMITEN expression NI date EN FILTERS
        if val.get("type") in ["expression", "date"]:
            continue

        # Si es field → normalizar referencia
        if val.get("type") == "field":
            vobj = val.get("object")
            vpth = resolve_path_from_root(schema, vobj, val.get("path"))
            val["path"] = _fix_double_c(vpth)

        clean.append({
            "field": field_path,
            "operator": operator,
            "value": val
        })

    return clean


def normalize_actions(actions, schema):
    """
    Enhanced normalizer supporting:
    - CREATE (single or bulk via filters)
    - UPDATE (single path update OR bulk via filters, but NOT both)
    - DELETE (with normalized filters)
    """

    out = []

    for a in actions or []:

        op = (a.get("operation") or "").upper()
        tgt = a.get("target", {}) or {}

        # ----------------------------------------------------------------------
        # 🔵 COMMON EXTRACTS
        # ----------------------------------------------------------------------
        target_obj     = tgt.get("object")
        target_path    = tgt.get("path")
        target_filters = tgt.get("filters", [])

        # Guarantee list
        if target_filters is None:
            target_filters = []
        if not isinstance(target_filters, list):
            target_filters = []

        # ----------------------------------------------------------------------
        # 🟩 CREATE (supports filters)
        # ----------------------------------------------------------------------
        if op == "CREATE":

            fields = a.get("value", {}).get("fields", {})
            fields_norm = normalize_create_value_fields(fields, schema)

            # Always path=None for CREATE
            normalized_target = {
                "object": target_obj,
                "path": None
            }

            # Bulk CREATE (filters)
            if target_filters:
                cleaned_filters = _normalize_filter_list(target_filters, target_obj, schema)
                normalized_target["filters"] = cleaned_filters

            out.append({
                "operation": "CREATE",
                "target": normalized_target,
                "value": {"fields": fields_norm}
            })
            continue

        # ----------------------------------------------------------------------
        # 🟧 UPDATE (supports normal update OR bulk via filters)
        # ----------------------------------------------------------------------
        if op == "UPDATE":

            val = a.get("value") or {}

            # CASE A → Bulk UPDATE (filters present)
            if target_filters:

                cleaned_filters = _normalize_filter_list(target_filters, target_obj, schema)

                normalized_target = {
                    "object": target_obj,   # must be event root object
                    "path": None,           # path MUST be null for bulk updates
                    "filters": cleaned_filters
                }

                out.append({
                    "operation": "UPDATE",
                    "target": normalized_target,
                    "value": _normalize_value_block(val)
                })
                continue

            # CASE B → Normal UPDATE (no filters, must have path)
            normalized_target = {
                "object": target_obj,
                "path": _fix_double_c(target_path)
            }

            out.append({
                "operation": "UPDATE",
                "target": normalized_target,
                "value": _normalize_value_block(val)
            })
            continue

        # ----------------------------------------------------------------------
        # 🔴 DELETE (with normalized filters)
        # ----------------------------------------------------------------------
        if op == "DELETE":

            cleaned_filters = _normalize_filter_list(target_filters, target_obj, schema)

            out.append({
                "operation": "DELETE",
                "target": {
                    "object": target_obj,
                    "filters": cleaned_filters
                },
                "value": None
            })
            continue

        # ----------------------------------------------------------------------
        # Unknown op → ignore silently
        # ----------------------------------------------------------------------
        continue

    return out



# ---------------------------------------------------------
# ✅ Main Extractor
# ---------------------------------------------------------

def extract_action_triggers_with_llm(user_message, current_state, previous_summary=None):

    schema = build_model_schema()
    available_models = list(schema.keys())

    print(f"\n\nSchema: {schema}\n\n")

    print(f"\n\nAvailable_models: {available_models}\n\n")

    # -----------------------------------------------------
    # ✅ STRICT SYSTEM PROMPT (no cambia formato de salida)
    # -----------------------------------------------------
    system_prompt = f"""
        You are a CPQ Action Trigger extraction engine.

        ⚠️ STRICT REQUIREMENTS — DO NOT VIOLATE ⚠️
        - You MUST output EXACTLY the JSON structure below (no extra keys, no different formats).
        - Do NOT invent operators.
        - Do NOT invent action types.
        - If the user does NOT specify conditions, set "conditions": null.

        ========================================================
        ✅ FIELD NAME SELECTION (VERY IMPORTANT)
        ========================================================
        - Pick object names ONLY from AVAILABLE_MODELS.
        - Pick field names ONLY from MODEL_SCHEMA below.
        - NEVER guess names outside MODEL_SCHEMA.
        - Custom objects and custom fields ALWAYS end with __c, but it’s very likely that the user won’t include that suffix.
        If any object or field matches a custom object or custom field, always use it with the __c at the end.

        ========================================================
        ✅ ALLOWED event_type.action
        ========================================================
        "create", "update", "delete" ONLY.

        ========================================================
        ✅ CONDITIONS FORMAT (STRICT)
        ========================================================
        conditions MUST ALWAYS be:

        {{
        "logic": "AND" | "OR",
        "items": [
            {{
            "alias": "optional_alias_or_null",
            "left": {{
                "object": "<event_root_object>",
                "path": "<field_or_relation_path>"
            }},
            "operator": "== | != | > | < | >= | <= | contains | in | not in",
            "right": {{
                <VALUE FORMAT>
            }}
            }}
        ]
        }}

        STRICT RULES:
        - "left.object" MUST ALWAYS be event_type.object_type (the event root).
        - Relationship navigation MUST go in "left.path", chosen ONLY from MODEL_SCHEMA.
        Example: quote_line → quote → account → tier__c  →  "quote.account.tier__c"
        - When comparing to the same external object (e.g., <CUSTOM_OBJECT>__c) across multiple items,
        reuse the SAME alias. If the user doesn't provide one, use the first two letters of the object
        (e.g., customobject__c → "co").

        ========================================================
        ✅ RULES FOR CREATE ACTIONS (STRICT AND MANDATORY)
        ========================================================
        When "operation" = "CREATE", the structure of the action MUST be:

        {{
        "operation": "CREATE",
        "target": {{
            "object": "<object_to_create>"
        }},
        "value": {{
            "fields": {{
            "<field_name>": {{
                <VALUE FORMAT>
            }}
            }}
        }}
        }}

        STRICT RULES FOR CREATE:
        - "target.path" MUST be omitted or null. Only "object" is allowed.
        - "value.type" MUST NOT exist. Instead, "value.fields" MUST exist.
        - "value.fields" MUST be an object containing 1 or more field entries.
        - Each entry inside "value.fields" MUST follow the normal VALUE structure.
        - NEVER output a CREATE action where "value" is a single field block.
        - NEVER output: {{"value": {{"type": "...", "object": "...", "path": "..."}}}}
        - NEVER output: {{"value": {{"data": "..."}}}}
        These are INVALID for CREATE.
        - If you need a date (like today, tomorrow, or date math), use type="date" with a formula like:
        "today()", "today() + 3 days", "today() + 12 months", "tomorrow()", or "today() + max(quote_line.term) months".

        ========================================================
        ✅ RULES FOR UPDATE ACTIONS (STRICT)
        ========================================================

        [
        {{
            "operation": "UPDATE",
            "target": {{
                "object": "<object>", 
                "path": "<field_or_null>"
            }},
            "value": {{
                <VALUE FORMAT>
            }}
        }}
        ]

        STRICT UPDATE RELATIONSHIP RULES:
        - ALWAYS include type key inside value
        - In UPDATE actions, "target.object" MUST ALWAYS be the same as event_type.object_type.
        - Relationship traversal MUST go ONLY inside "target.path".
        - NEVER set target.object to a related object (e.g., "account", "quote", "contract").

        ========================================================
        ✅ FILTERS FOR CREATE AND UPDATE (STRICT AND MANDATORY)
        ========================================================
        CREATE and UPDATE actions MAY optionally include filters inside target.

        This enables bulk operations.

        When filters are present, the structure MUST be:

        "target": {{
            "object": "<object_name>",
            "filters": [
                {{
                    "field": "<field_path_in_target>",
                    "operator": "== | != | > | < | >= | <= | contains | in | not in",
                    "value": {{
                        "type": "static" | "field",
                        "data": <literal_if_static>,
                        "object": "<object_if_field>",
                        "path": "<path_if_field>"
                    }}
                }}
            ]
        }}

        STRICT RULES:
        - Filters are OPTIONAL for CREATE and UPDATE.
        - If filters exist, they MUST follow the exact format shown above.
        - Filters MUST ALWAYS be a list (one or more).
        - "field" refers to a path INSIDE THE TARGET OBJECT.
          Example: "account.id", "quote.account.tier__c", "status"
        - For field-based values, ALWAYS include type="field", and include object/path.
        - For static values, type="static" + data=<literal>.
        - "operator" MUST NOT be invented — ONLY use allowed operators.
        - Filters combine with AND logic.
        - DO NOT use expression or date types inside filter values.
          (Only static or field allowed.)

        ========================================================
        ✅ BULK CREATE (how LLM should output it)
        ========================================================
        When a CREATE action uses filters, it MUST follow this exact structure:

        {{
          "operation": "CREATE",
          "target": {{
            "object": "<object_to_create>",
            "filters": [ ... ]
          }},
          "value": {{
            "fields": {{
                "<field_name>": {{
                    <VALUE FORMAT>
                }}
            }}
          }}
        }}

        - "target.path" MUST NOT appear in CREATE.
        - "filters" MUST ONLY be inside target (not inside value).
        - For each record returned by the filters, create ONE new record.

        ========================================================
        ✅ BULK UPDATE (how LLM should output it)
        ========================================================
        When an UPDATE action uses filters, it MUST follow this structure:

        {{
          "operation": "UPDATE",
          "target": {{
            "object": "<event_root_object>",
            "path": null,
            "filters": [ ... ]
          }},
          "value": {{
            <VALUE FORMAT>
          }}
        }}

        STRICT RULES FOR BULK UPDATE:
        - "target.object" MUST ALWAYS be the event root object.
        - "path" MUST be null when using filters.
        - Filters restrict WHICH records will be updated.
        - Updates apply to ALL matched records.

        --------------------------------------------------------
        ✅ DELETE
        --------------------------------------------------------
        {{
        "operation": "DELETE",
        "target": {{
            "object": "<object_to_delete>",
            "filters": [
            {{
                "field": "<field_path_in_target>",
                "operator": "== | != | > | < | >= | <= | contains | in",
                "value": {{
                    <VALUE FORMAT>
                }}
            }}
            ]
        }}
        }}

        STRICT RULES FOR DELETE:
        - "filters" is ALWAYS a list of one or more filter objects.
        - Each filter defines how to match records in the target model.
        - "field" refers to a path inside the target object (e.g., "quote.account.id").
        - "value" describes what to compare against (can be static or another field).
        - If multiple filters are provided, they are combined with AND logic.
        - Do NOT use "path": "self" unless the trigger explicitly says “delete the same record”.
        - NEVER include "value" outside of the filter list in DELETE actions.

        ========================================================
        ✅ ABSOLUTE RULES FOR VALUE FORMAT (STRICT AND MANDATORY)
        ========================================================
        These rules define exactly how any value must be returned for CREATE, UPDATE, and DELETE.

        Valid formats for each VALUE TYPE inside CREATE:

        A) static:
        {{
            "type": "static",
            "data": <LITERAL_VALUE>
        }}

        B) field:
        {{
            "type": "field",
            "object": "<object_name>",
            "path": "<field_path>"
        }}

        C) expression:
        {{
            "type": "expression",
            "formula": "<EXPRESSION_FORMULA>"
        }}

        D) date:
        {{
            "type": "date",
            "formula": "<DATE_FORMULA>"
        }}

        ========================================================
        ✅ EXPRESSION FORMULAS (STRICT ALLOWED SYNTAX)
        ========================================================
        When value.type = "expression", the "formula" string MAY contain:

        1) 🔢 Arithmetic operations:
        - +, -, *, /
        - Parentheses: ( ... )

        2) 🧠 Comparisons (ONLY inside IF()):
        - ==, !=, >, <, >=, <=

        3) 🧩 Conditional logic:
        - IF(condition, value_if_true, value_if_false)

        4) 🔢 Math functions:
        - ROUND(x, n)
        - FLOOR(x)
        - CEIL(x)
        - ABS(x)
        - MAX(a, b, ...)
        - MIN(a, b, ...)

        5) 🔠 String functions:
        - CONCAT(a, b, ...)
        - UPPER(s)
        - LOWER(s)
        - TRIM(s)
        - LEFT(s, n)
        - RIGHT(s, n)
        - REPLACE(s, a, b)

        6) 📚 Collection functions:
        - SUM(object.field)
        - AVG(object.field)
        - MIN(object.field)
        - MAX(object.field)
        - COUNT(object.field)

        7) 🔗 Field references exactly as they appear in MODEL_SCHEMA:
        Examples:
        - quote_line.quantity
        - quote_line.unit_price
        - quote.account.tier__c
        - quote.quote_line.quantity

        STRICT RULES:
        - The expression MUST be a single valid formula string.
        - NEVER wrap formulas in quotes.
        - NEVER invent functions not listed above.
        - ALWAYS refer to fields exactly using the MODEL_SCHEMA.
        - NEVER use "self" or undefined objects.

        ========================================================
        ✅ DISCOUNT RULES (STRICT)
        ========================================================
        When setting a discount on quote or quote_line:
        - If user uses "%" or mentions "percentage" → use discount_percentage (number) AND set discount_type="percentage".
        - If user uses "$" or a currency → use discount_amount (number) AND set discount_type="amount".
        - If no hint → default to discount_percentage + discount_type="percentage".
        ALWAYS produce TWO updates when writing a discount:
        1) update discount_amount/discount_percentage with a normalized number (strip symbols)
        2) update discount_type with "amount" or "percentage"

        ========================================================
        ✅ DATA NORMALIZATION RULES (STRICT)
        ========================================================
        - If number: must be returned as a real JSON number (30), NEVER as a string ("30").
        - Strip "%", "$", commas, etc. before converting.
        - If string: must stay as a string.
        - If boolean: must be true/false lowercase.
        - If field reference: use type="field" and provide object/path.

        ========================================================
        ✅ ALIAS RULES (VERY IMPORTANT)
        ========================================================
        - Alias is ONLY used when comparing a field from the event object to a field of another object (field-to-field comparison).
        - If "right.type" = "field", alias MAY be used.
        - If "right.type" = "field" AND right.object appears multiple times → use SAME alias for all items.
        - If "right.type" = "static":
            → alias MUST ALWAYS be null.
            → do NOT generate alias names like "ql", "qt", "obj", etc.
        - NEVER assign alias for static comparisons.

        ALIAS MUST ALWAYS BE NULL unless ALL of the following are true:

        1) right.type = "field"
        2) The right.object appears in TWO OR MORE condition items (repeated comparison).
        3) The repeated object is external to the event root (e.g., comparing event fields to the same custom object or the same model more than once).

        If ANY of these conditions is false:
        → alias MUST be null.
        → NEVER generate alias for static, date, or expression values.
        → NEVER generate alias for single field-to-field comparisons.
        → NEVER generate alias names automatically (like "op", "qt", "ql", etc.).

        ========================================================
        ✅ YOU MUST ALWAYS RETURN NON-EMPTY "description" and "agent_message".
        - description: short 1-line summary of the trigger.
        - agent_message: short helpful line for the user (not technical).

        ========================================================
        ✅ MODEL_SCHEMA (USE THIS EXCLUSIVELY)
        ========================================================
        {json.dumps(schema, indent=2)}

        ========================================================
        ✅ AVAILABLE_MODELS (USE THIS EXCLUSIVELY)
        ========================================================
        {json.dumps(available_models, indent=2)}

        ========================================================
        ✅ RESPONSE FORMAT (STRICT)
        ========================================================
        You MUST ALWAYS return:

        {{
        "create_action_trigger": [
            {{
            "data": {{
                "description": "<string>",
                "event_type": {{"object_type": "<object>", "action": "<create|update|delete>"}},
                "conditions": null OR EXACT conditions structure,
                "actions": [ EXACT actions list ],
                "active": true,
                "priority": null
            }},
            "completed": true|false
            }}
        ],
        "agent_message": "<string>",
        "summary": "<string>"
        }}

        - You MUST always include a "priority" key inside data, right after "actions".
        - If the user does NOT specify a priority, ALWAYS set "priority": null.
        - Do NOT set a default yourself. Just put null.


        REMEMBER ALWAYS produce TWO updates when writing a discount:
        1) update discount_amount/discount_percentage with a normalized number (strip symbols)
        2) update discount_type with "amount" or "percentage"
        """

    # -----------------------------------------------------
    # ✅ User Prompt
    # -----------------------------------------------------
    user_prompt = f"""
      User message: "{user_message}"

      Current state:
      {json.dumps(current_state, indent=2)}

      Previous summary:
      {previous_summary or "None"}

      Return ONLY the JSON. Do NOT add text outside JSON.
      """

    # -----------------------------------------------------
    # ✅ LLM CALL
    # -----------------------------------------------------
    response = client.chat.completions.create(
        model=OPENAI_MODEL,
        messages=[
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": user_prompt},
        ],
        temperature=0.2,
    )

    raw = response.choices[0].message.content.strip()
    logging.info(f"\n🔍 Raw GPT Response:\n{raw}\n")

    try:
        result = json.loads(raw)
    except Exception:
        logging.error("❌ JSON decode failed")
        return None

    # -----------------------------------------------------
    # 🔧 Post-fix Sanitizer (NO cambia formato; solo corrige)
    # -----------------------------------------------------
    def _sanitize_result_structure(r):
        try:
            cats = r.get("create_action_trigger", [])
            for t in cats:
                data = t.get("data", {})

                # Ensure description & agent_message non-empty
                if not data.get("description"):
                    data["description"] = "Action trigger extracted from user instruction."
                if not r.get("agent_message"):
                    r["agent_message"] = "Trigger interpreted and formatted. Review before saving."
                if not r.get("summary"):
                    r["summary"] = "Parsed trigger with validated structure."

                # Normalize event_type
                evt = normalize_event_type(data.get("event_type"), available_models)
                data["event_type"] = evt

                # Fix and enrich conditions
                cond = data.get("conditions")
                if cond and isinstance(cond, dict):
                    items = cond.get("items") or []
                    event_root = evt["object_type"] if evt else None

                    for item in items:
                        # Ensure left.object is the event root
                        if event_root and item.get("left"):
                            item["left"]["object"] = event_root

                            # Resolve/repair left.path using schema
                            lp = item["left"].get("path")
                            item["left"]["path"] = resolve_path_from_root(schema, event_root, lp)

                        # Fix right.path double __c
                        rgt = item.get("right") or {}
                        if isinstance(rgt, dict) and rgt.get("path"):
                            rgt["path"] = _fix_double_c(rgt["path"])

                        # Auto alias "pt" if right references pricingtable__c and alias missing
                        if rgt.get("type") == "field" and rgt.get("object") == "pricingtable__c":
                            if not item.get("alias"):
                                item["alias"] = "pt"

                    # If after sanitation items is empty, set to None
                    if not items:
                        data["conditions"] = None
                    else:
                        cond["items"] = items
                        data["conditions"] = cond
                else:
                    # Respect user's intent: if not specified, keep null
                    data["conditions"] = None

                # Fix action paths and value paths
                acts = data.get("actions") or []
                for a in acts:
                    tgt = a.get("target") or {}
                    # For UPDATE/DELETE, we may sanitize paths; for CREATE, force None later in normalize.
                    if tgt.get("path"):
                        tgt["path"] = _fix_double_c(tgt["path"])

                    # DO NOT flatten CREATE value into {"type": null}:
                    op = (a.get("operation") or "").upper()
                    val = a.get("value") or {}

                    if op == "CREATE":
                        # Keep fields structure; just sanitize any inner paths
                        fields = val.get("fields", {})
                        if isinstance(fields, dict):
                            new_fields = {}
                            for fname, spec in fields.items():
                                if not isinstance(spec, dict):
                                    continue
                                if spec.get("type") == "field":
                                    obj = spec.get("object")
                                    pth = spec.get("path")
                                    if isinstance(obj, str) and isinstance(pth, str):
                                        new_fields[fname] = {
                                            "type": "field",
                                            "object": obj,
                                            "path": _fix_double_c(pth),
                                        }
                                    else:
                                        # drop malformed to avoid {"type": null}
                                        continue
                                elif spec.get("type") == "static":
                                    new_fields[fname] = {"type": "static", "data": spec.get("data")}
                                elif spec.get("type") == "expression":
                                    new_fields[fname] = {"type": "expression", "formula": spec.get("formula")}
                                elif spec.get("type") == "date":
                                    new_fields[fname] = {"type": "date", "formula": spec.get("formula")}
                                else:
                                    # drop unknown
                                    continue
                            a["value"]["fields"] = new_fields
                        # Ensure target.path is None for CREATE
                        a["target"]["path"] = None
                    if op == "UPDATE":
                        # For UPDATE, sanitize value.path if present
                        if isinstance(val, dict) and val.get("path"):
                            val["path"] = _fix_double_c(val["path"])

                    if op == "DELETE":
                        tgt = a.get("target") or {}
                        filters = tgt.get("filters", [])
                        new_filters = []
                        for f in filters:
                            if not isinstance(f, dict):
                                continue
                            val = f.get("value")
                            if isinstance(val, dict) and val.get("path"):
                                val["path"] = _fix_double_c(val["path"])
                            new_filters.append({
                                "field": f.get("field"),
                                "operator": f.get("operator"),
                                "value": val
                            })
                        tgt["filters"] = new_filters
                        a["target"] = tgt

        except Exception:
            logging.exception("Post-fix sanitizer failed")

    _sanitize_result_structure(result)

    # -----------------------------------------------------
    # ✅ Final normalization & completed (controlado por ti)
    # -----------------------------------------------------
    norm = []
    for trig in result.get("create_action_trigger", []):
        data = trig.get("data", {}) or {}

        # Normalize event_type once more to be safe
        evt = normalize_event_type(data.get("event_type"), available_models)

        conditions = normalize_conditions(data.get("conditions"))
        actions = normalize_actions(data.get("actions"), schema)

        def is_valid_event(e):
            return bool(e and e.get("object_type") in available_models and e.get("action") in ["create", "update", "delete"])

        def is_valid_actions_list(a):
            return actions_are_valid(a)

        completed_flag = is_valid_event(evt) and is_valid_actions_list(actions)

        # Guarantee non-empty description/agent_message
        if not data.get("description"):
            data["description"] = "Action trigger extracted from user instruction."
        if not result.get("agent_message"):
            result["agent_message"] = "Trigger interpreted and formatted. Review before saving."
        if not result.get("summary"):
            result["summary"] = "Parsed trigger with validated structure."

        # -----------------------------
        # 🔥 PRIORITY NORMALIZATION
        # -----------------------------
        priority_value = data.get("priority")

        # Si el LLM no lo puso o está null → default = 100
        if priority_value in (None, "", "null"):
            priority_value = 100

        # Si viene como string numérica → convertir
        try:
            priority_value = int(priority_value)
        except:
            priority_value = 100

        norm.append({
            "data": {
                "description": data.get("description"),
                "event_type": evt,
                "conditions": conditions,   # may be None
                "actions": actions,
                "active": data.get("active", True),
                "priority": priority_value
            },
            "completed": completed_flag,
        })

    result["create_action_trigger"] = norm
    return result
