# Generated by Django 5.1.5 on 2025-02-16 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("salesforce", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="salesforcetoken",
            name="refresh_token",
            field=models.TextField(blank=True, null=True),
        ),
    ]
