# Generated by Django 5.1.5 on 2025-05-14 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("salesforce", "0002_salesforcetoken_refresh_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="salesforcetoken",
            name="expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="salesforcetoken",
            name="issued_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="salesforcetoken",
            name="issued_at_raw",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
